README.md, lib/suspenders/app_builder.rb, spec/features/heroku_spec.rb
Rails 4.2.0 uses a `ENV['RAILS_SERVE_STATIC_FILES']` variable to determine by
default whether to server static files. We should use that community
convention rather than the `rails_serve_static_assets` gem, which is loaded by
`rails_12factor`. Removing that coupling also allows non-Heroku users to use
this convention.
When we remove our reliance on that gem, the remaining half of
`rails_12factor` that we still want to use in Heroku environments is the
`rails_stdout_logging` gem.
Extract a `serve_static_files_line` helper method as a way to reliably append
to the `config/environments/production.rb` file.
Use double quotes instead of single quotes on changed lines and the lines
around them.
=> Use only rails_stdout_logging, not rails_12factor

templates/smtp.rb
In Heroku's docs for
[Mandrill](https://devcenter.heroku.com/articles/mandrill) and
[SendGrid](https://devcenter.heroku.com/articles/sendgrid#ruby-rails), they
suggest using `heroku.com`.
Make this clearer for implementers.
=> Improve SMTP_DOMAIN comment

templates/unicorn.rb
Fix:
> Line is too long. [91/80]
Fix:
> Unused block argument - server.
> Unused block argument - worker.
> You can omit all the arguments if you don't care about them.
=> Create Hound-compliant config/unicorn.rb

.travis.yml, templates/travis.yml.erb
Builds start sooner and run faster. Open source builds on the container
infrastructure also get to use the bundle cache. See:
http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
This has worked extremely well on all projects I've tried it on thus far.
=> Use Travis container infrastructure

templates/Gemfile.erb
* Fixes Rails 4.2 named route deprecation warnings
=> Upgrade RSpec to 3.1.0

lib/suspenders/app_builder.rb
Before:
```
* [Style](http://github.com/thoughtbot/guides/blob/master/style)
```
...and it renders "## Deploying" on the same line as the Style link.
After:
```
* [Style](http://github.com/thoughtbot/guides/blob/master/style)
```
=> Prepend a new line before adding to README

lib/suspenders/app_builder.rb
With this setting on, Rails will happily turn a POST to the UsersController 
from this:
{ name: "Ralph" }
Into this:
{ users: { name: "Ralph" }, name: "Ralph" }
This means that `params.require(:user).permit(:name)` will not raise an error,
even if the developer forgets to nest their parameters inside a top-level
`user` key.
It is enabled for JSON by default. This change turns it off for every format.
=> Turn off parameter wrapping

templates/travis.yml.erb
The documentation gives this as the correct way to turn off build
notifications:
```yaml
notifications:
email: false
```
This maps to `{ "notifications" => { "email" => false } }` in Ruby.
We currently set it to:
```yaml
notifications:
email:
- false
```
This maps to `{ "notifications" => { "email" => [false] } }` (note that
`false` is in an array). Because of this, Travis does not turn off email
notifications.
Docs: http://docs.travis-ci.com/user/notifications/
=> Turn off Travis email notifications

templates/development_seeds.rb
We wrap the `dev:prime` task in `if Rails.env.development?`. CI runs in the test environment. Because the environments don't match, the `dev:prime` task is never defined in CI, and CI crashes.
=> Do run `rake dev:prime` on CI

lib/suspenders/actions.rb, lib/suspenders/app_builder.rb
Before:
```ruby
config.action_mailer.default_url_options = { host: 'ENV.fetch("HOST")' }
```
After:
```ruby
config.action_mailer.default_url_options = { host: ENV.fetch("HOST") }
```
=> Don't set default_url_options to a string

lib/suspenders/app_builder.rb
By default, Rails 4 will not serve your assets:
https://devcenter.heroku.com/articles/rails-4-asset-pipeline#serve-assets
We use an environment variable to tell Rails to serve static files:
```ruby
config.serve_static_files = ENV['RAILS_SERVE_STATIC_FILES'].present?
```
..but we were not automatically setting that environment variable on Heroku.
Now we are.
=> Tell Heroku to serve static files

templates/suspenders_layout.html.erb.erb
When opening layout.html.erb to change the title, if can be off-putting
to traverse down a nest of discovery in order to know that one should
change the title in config/locales/*.yml. Add a note right there so that
people don't have to hunt.
=> Document how to use the #title helper

CONTRIBUTING.md, README.md
* It's unreasonable to expect contributors to
read and comprehend thoughtbot/guides.
* It's reasonable to expect they should fix Hound violations.
* Shorten a few other sentences.
* Delete unnecessary words.
* Move note about Ruby version inside `CONTRIBUTING.md` document.
=> Refer to Hound in addition to thoughtbot/guides

README.md
I had a hard time comprehending the Flutie gem's description before I realized it must be missing the `page_title` bit.
=> Include missing word in the Flutie description.

lib/suspenders/app_builder.rb, spec/features/heroku_spec.rb
At the moment, in order to use the deploy script, an user must set it as
executable.
This sets the file as executable after creating it, following the logic
employed for the `bin/setup` script. It also adds tests for both of
the files, in order to prevent regression
=> Set bin/deploy script as executable

lib/suspenders/app_builder.rb, templates/sample.env
It defaults to `HOST`.
Related with issue: https://github.com/thoughtbot/suspenders/issues/491
=> Add ASSET_HOST to sample.env

README.md
* Include 2015 in the copyright.
* Update logo to use new HTTPS version.
* Change header from "Credits" to "About thoughtbot".
* Move "thank you" to contributors section.
* Make "About thoughtbot" the last thing in the README,
with the copyrights grouped closer to the LICENSE information.
* Link to LICENSE.
* Make the community link more obvious that we have other projects.
* Finish with a CTA to hire us.
* Include `utm_source` codes to improve tracking.
=> Update thoughtbot section of README

templates/spec_helper.rb
https://relishapp.com/rspec/rspec-mocks/v/3-0/docs/verifying-doubles/partial-doubles
"When the verify_partial_doubles configuration option is set, the same
argument and method existence checks that are performed for
object_double are also performed on partial doubles. You should set
this unless you have a good reason not to. It defaults to off only for
backwards compatibility."
=> Enable verify_partial_doubles for RSpec

lib/suspenders/app_builder.rb, lib/suspenders/generators/app_generator.rb
This step generates an unneeded `app/views/refills/_flashes.html.erb`, but there's already `app/views/application/_flashes.html.erb`. Contents of the seemingly unneeded component:
```erb
<div class="flash-success">
<span>This is a success message <a href="#">with a link</a></span>
</div>
<div class="flash-error">
<span>This is an error message <a href="#">with a link</a></span>
</div>
<div class="flash-notice">
<span>This is an notice message <a href="#">with a link</a></span>
</div>
<div class="flash-alert">
<span>This is an alert message <a href="#">with a link</a></span>
</div>
```
Related: https://github.com/thoughtbot/suspenders/issues/537
=> Avoid generation of extra _flashes view

Gemfile.lock, templates/Gemfile.erb, templates/spec_helper.rb
It was removed due to a return status bug which would mark failed builds as
successful, and is now fixed.
This reverts commit 6ece3c4bbea3825802e16c41724fa062b91b7c29.
Related with: https://github.com/thoughtbot/suspenders/issues/313
=> Add SimpleCov

lib/suspenders/app_builder.rb, templates/Gemfile.erb, templates/browserslist
Should we add a default config file, as well? It would allow us to [define which browser versions](https://github.com/ai/autoprefixer-rails#ruby-on-rails) we want to support…where would I put that `browserslist` here in Suspenders?
=> Add Autoprefixer

README.md
We recently added Autoprefixer Rails to Suspenders (https://github.com/thoughtbot/suspenders/commit/7df323348714f7495bd296d8f3ae18baf89d8852), but forgot to add it to the gem list in the readme :smile:
=> Add mention of Autoprefixer Rails gem to readme

templates/sample.env
This is necessary for compiling assets (when needed to run with compiled assets
in dev).
=> Provide EXECJS_RUNTIME env variable

templates/_flashes.html.erb
Generally speaking, it’s best practice to style off `class`’s instead of `id`’s. There are exceptions, but in this case, I would consider the `id` of `flash` not very useful, so this swaps it for a `class` instead. Also, the flash key on Line 4 was already being output as a class; this unifies the two.
=> Swap flash id for a class

templates/rails_helper.rb
This ensures that the `require` order is the same on all machines, including CI.
For example, we mainly use OS X as our local development machines, while CI runs
on Linux. We've run into ordering issues before due to the different OS's, and
this changes has historically fixed it.
=> Require spec/support files in alphabetical order

spec/features/github_spec.rb, spec/features/heroku_spec.rb, spec/features/new_project_spec.rb, spec/spec_helper.rb
* Run Suspenders only once in `new_project_spec.rb`.
* Should be about 17x faster.
=> Improve test suite speed

README.md, lib/suspenders/app_builder.rb, lib/suspenders/generators/app_generator.rb, spec/features/new_project_spec.rb, templates/hound.yml
* Turn on JavaScript but not CoffeeScript by default.
* Help avoid configuration mistakes by providing this stub
and a link to the configuration page.
=> Add default .hound.yml file

lib/suspenders/app_builder.rb, lib/suspenders/generators/app_generator.rb
* refills/flashes does not exist and fails import
* As per issue #537 and PR #546
I recognize that this is not the ultimate solution, this is still broken but this could be a possible solution and would have to change the refills gem.
We may want to consider scrapping the current flashes partial in favor of the refills defined ones instead.
=> We still need to import refills scss

lib/suspenders/app_builder.rb, templates/dev.rake
Using db/seeds for data which must be loaded in a production environment
is a standard Rails convention.  We cause confusion by using the word
"seed" elsewhere in a Rails app, where that is not the context.
The `dev:prime` task is actually providing local fake/sample data for
developers to see the app in use, but not production-required data to
actually run the application.
=> Rename development data concept to avoid db/seeds confusion

lib/suspenders/app_builder.rb, templates/sample.env
The .env should not touch $HOST, since that is controlled by the shell
and changing it can lead to surprises, failures, and even crashes.
=> Do not touch $HOST in .env

templates/circle.yml.erb
The current circle.yml template does not set the env vars before running the build, which can lead to build failures. It also doesn't set a db setup command, which causes Circle to run `rake db:create
db:schema:load` by inference.
This PR sets the command to copy env vars from the .sample.env file post checkout, following CircleCI's recommendation for this type of operation: https://circleci.com/docs/manually#checkout
This allows for the env vars to be available for all steps of the build,making it safe to run commands that load an environment, particularly`rake`.
It also sets the database setup command to `bundle exec rake db:setup` to keep in line with the Suspenders setup script, even though I believe it is technically equivalent to the inferred command.
=> Update CircleCI config

lib/suspenders/app_builder.rb, spec/features/new_project_spec.rb
Reason for change:
* In 9d27905884540e44109cc66630062101307f150a, `HOST` was replaced for  `APPLICATION_HOST`
* Some instances were missed, leading to errors on deploy from a fresh build.
What the change was:
* Replace remaining `HOST` instances with `APPLICATION_HOST`
* Add regression spec
Original commit: https://github.com/thoughtbot/suspenders/commit/9d27905884540e44109cc66630062101307f150a
=> Fix HOST/APPLICATION_HOST env error

templates/Gemfile.erb, templates/rails_helper.rb
Removes capybara-webkit minimum version specification in Gemfile,
relying on bundler to install latest available release.
See: http://blog.arkency.com/2015/02/upgrade-capybara-webkit-to-1-dot-4-and-save-your-time/
[fixes #550]
cc @jferris @croaky for reviews. Thank you!
=> Configure capybara-webkit to block unknown URLs

lib/suspenders/app_builder.rb, lib/suspenders/generators/app_generator.rb, templates/Gemfile.erb, templates/rails_helper.rb, templates/shoulda_matchers_config_rspec.rb
The recent release of Shoulda Matchers 3.0 introduces some changes,
namely requiring configuration in order to operate.
The absence of the file leads to hard to decipher errors: they indicate
methods are missing and can lead to some frustration trying to
understand what is necessary to get Shoulda to behave correctly.
This PR introduces a build step to provide a config file for in order
for it to be enabled "out-of-the-box". It opts in to enable interaction
with all of Rails, as this seems the principle of least surprise.
=> Provide Shoulda Matchers config

lib/suspenders/app_builder.rb, lib/suspenders/generators/app_generator.rb, spec/features/new_project_spec.rb, templates/factories.rb
Our guides say
> Use one factories.rb file per project.
and the factory_girl_rails documentation says
> If you use factory_girl for fixture replacement and already have a
> factories.rb file in the directory that contains your tests,
> factory_girl_rails will insert new factory definitions at the top of
> factories.rb.
Generating this file will allow use to conform to our guides more
easily. Will close #622.
=> Generate empty spec/factories.rb file

templates/puma.rb
Using a simple Suspenders application, I profiled memory usage for our
default configuration, as well as a few others. I found the following:
* A Puma cluster uses a master process and multiple worker processes.
The amount of memory used by a cluster is equal to the memory usage of
the master process plus the possible bloated size of a worker process
times the number of worker processes.
* At boot, a simple Suspenders application uses about 117MB for the
master process and 109M for each worker.
* After the first request is served, a process increases to around 117M,
like the master process.
* The amount of potential bloat increases with each thread, because it's
possible for every thread to be handling a bloated request at once.
* Using [siege], I determined that the expected bloat in a …
=> Reduce number of Puma processes and threads

README.md, lib/suspenders/app_builder.rb, lib/suspenders/generators/app_generator.rb, spec/features/new_project_spec.rb, templates/Gemfile.erb
I typically search the logs to find parameters, response codes and
stacktraces. Although we don't need to see what assets have been loaded,
those logs take up more space than the aforementioned ones.
`quiet_assets` hide the assets logs in development, making the log for
the landing page on my current suspenders project go from 64 lines
detailing assets, to 13 relevant lines.
=> Add quiet_assets as development dependency

lib/suspenders/generators/app_generator.rb
A spec run in master looks like:
```
[Simple Form] Simple Form is not configured in the application and will use the default values. Use `rails generate simple_form:install` to generate the Simple Form configuration.
[Simple Form] Simple Form is not configured in the application and will use the default values. Use `rails generate simple_form:install` to generate the Simple Form configuration.
[Simple Form] Simple Form is not configured in the application and will use the default values. Use `rails generate simple_form:install` to generate the Simple Form configuration.
.
Finished in 22.78 seconds (files took 0.12645 seconds to load)
1 example, 0 failures
```
If we configure SimpleForm earlier in the process, we get the warning
only once, during the generation of the initializer:
``` …
```
=> Configure SimpleForm earlier

lib/suspenders/app_builder.rb
It inherits production's, which reads the same environmental variable.
=> No need to configure action_mailer_host in staging

templates/bin_setup.erb
According to the current definition of the [dev:prime][task] Rake
task, chaining `db:setup` before `dev:prime` is unnecessary.
Additionally, the generated Rails application uses Bundler's [binstubs],
so we can replace `bundle exec rake` with `bin/rake`.
[task]: https://github.com/thoughtbot/suspenders/blob/bfd75f9f16f8557ddf91a069525d13f7bdc7ce8f/templates/dev.rake#L6
[binstubs]: http://bundler.io/v1.10/bundle_binstubs.html
=> Cleanup generated `bin/setup` file

templates/circle.yml.erb
There is no need to use `bundle exec` given we have binstub in `bin/`.
=> Config Circle to use rake binstub instead

lib/suspenders/generators/app_generator.rb
I changed the order of build inside customize_gemfile in app_generator.rb
Why:
I noticed that with a fresh gemset, apart from the dependencies that come with Suspenders, it was crashing during app generation while trying to configure simple_form, due to a missing "bundle install", which was meant to happen after that. I actually feel pretty dumb to open a pull request like this on such a great repo
=> Changed order in customize_gemfile in app_generator

spec/features/new_project_spec.rb
It appears that Spring has switched from using double-quotes in their
binstub to using single-quotes. The change has broken one of our tests,
where we are asserting that the binstub contains a line matching a
regular expression.
Update the regular expression to use single-quotes, to match those
created by the binstub generator.
=> Fix spring binstub test

lib/suspenders/app_builder.rb, spec/features/heroku_spec.rb
Bug found here, on a fresh suspenders app: https://circleci.com/gh/thoughtbot/automatic-holiday-dataviz/1
The circle configuration tries to deploy the build to the heroku staging
environment if it finishes successfully.
Because both the .circle.yml and bin/setup scripts
define the staging remote for git,
the build fails with a warning about the duplicate remote.
Only set the staging remote once, in the setup script.
Remove the redundant source definition from `circle.yml`
=> Fix Circle deploys by removing redundant remote

lib/suspenders/app_builder.rb, lib/suspenders/generators/app_generator.rb, spec/features/new_project_spec.rb, templates/Gemfile.erb
Bullet notifies automatically if there is any request in the application
where we are performing N+1 queries, or unused eager loading.
With this check we make sure we eager load what is needed, and nothing
more, without having to check each endpoint.
=> Add bullet as development dependency

lib/suspenders.rb, lib/suspenders/adapters/heroku.rb, lib/suspenders/app_builder.rb, lib/suspenders/generators/app_generator.rb, spec/adapters/heroku_spec.rb, spec/features/heroku_spec.rb, spec/spec_helper.rb, spec/support/fake_heroku.rb, spec/support/suspenders.rb
Improve testability for Heroku actions
Why:
* It was very coupled and difficult to test in isolation, there was pretty much one single integration test.
This change addresses the need by:
* Making it easier to test and reason about Heroku functionality we want to use, by allows for smaller, faster and more focused tests.
* Using mocks instead of depending on side effects because it was tricky to build a fake of the an AppBuilder, that has a lot of functionality and it is already being tested in our integration tests.
* Using a mockist approach, that ensures the correct methods are called with the right arguments (this last part is wip)
Interested in opinions before I go much further with this. /cc @tute
=> Improve testability

lib/suspenders/app_builder.rb, lib/suspenders/generators/app_generator.rb, templates/README.md.erb, templates/bin_setup.erb, templates/sample.env, templates/suspenders_gitignore
Heroku Local has replaced Foreman in the Heroku Toolbelt.
https://devcenter.heroku.com/changelog-items/692
The command `heroku local` has replaced `foreman`.
Heroku Local makes use of [Forego] to accomplish its tasks
and it is faster and has better cross-platform support.
[Forego]: https://github.com/ddollar/forego
=> Use Heroku Local (Forego) instead of Foreman

lib/suspenders/app_builder.rb, lib/suspenders/generators/app_generator.rb, spec/features/new_project_spec.rb
When testing features, we'd prefer to be notified of asset pipeline
issues as early as possible.
=> Raise on missing Sprockets assets in test

spec/features/new_project_spec.rb, templates/suspenders_layout.html.erb.erb
Identifying the language of the document is important for a number of
reasons:
* It allows braille translation software to substitute control codes
for accented characters, and insert control codes necessary to prevent
erroneous creation of Grade 2 braille contractions.
* Speech synthesizers that support multiple languages will be able to
orient and adapt to the pronunciation and syntax that are specific to
the language of the page, speaking the text in the appropriate accent
with proper pronunciation.
* Marking the language can benefit future developments in technology,
for example users who are unable to translate between languages
themselves will be able to use machines to translate unfamiliar
languages.
* Marking the language can also assist user agents in providing
definitions using …
=> Add lang attribute to html element in layout

NEWS.md, templates/Gemfile.erb
Why use just Pry or byebug when you can have the power of both?
This lets us use `next`, `continue`, `up`, etc. instead of a Pry
session; conversely, it gives us a full IRB environment inside of a
byebug session.
=> Use pry-byebug instead of just byebug

templates/i18n.rb
Suspenders [currently mixes-in][1] `AbstractController::Translation` in
specs [so that the `t()` helper method is available][2]. However, this
helper method produces unintuitive failure/error messages in certain
cases when used in specs:
1. Passing a missing translation key to `t()` in specs produces an RSpec
failure indicating that the text "translation missing" was not found,
instead of an exception indicating the key itself is missing from the
translations.
```
Failure/Error: expect(page).to have_content t("invalid_key")
expected to find text "translation missing: en.invalid_key" in
"All text on the page."
```
Additionally, when using this kind of expectation against `page` in a
feature spec, RSpec outputs the entire text of the page, which may fill
the terminal window and cause the …
=> Improve Errors for Invalid I18n Keys in Specs

templates/errors.rb
Fixing issue mentioned in #686 
TimeoutError has been deprecated and in favor of using Timeout::Error in ruby 2.3.0
=> Fix SMTP TimeoutError warning

README.md, bin/setup, lib/suspenders/adapters/heroku.rb, lib/suspenders/app_builder.rb, lib/suspenders/generators/app_generator.rb, spec/features/heroku_spec.rb, spec/features/new_project_spec.rb, spec/support/fake_heroku.rb, templates/app.json.erb, templates/bin_setup, templates/bin_setup_review_app.erb
Why:
* We have observed that running acceptance through Heroku Pipelines is a
better flow for code reviews, by allowing to show work in progress
earlier, and fixing issue before merging into master
This change addresses the need by:
* Creating a pipeline for the new app, and adding the staging and
production environments to it
* Adding a required `app.json` configuration file
* Setting `Rack::CanonicalHost` only in staging and production, and not
review apps (otherwise review apps redirect to staging)
* Adding a setup script for review apps to scale up workers to 1 and run migrations
```bash
if heroku pipelines &> /dev/null; then
do_it
else
printf 'You need heroku pipelines plugin. Run: heroku plugins:install heroku-pipelines'
fi
```
* needs to set up Circle CI with the new GitHub repo
* …
=> Introduce Heroku Pipelines support

NEWS.md, lib/suspenders/app_builder.rb, lib/suspenders/generators/app_generator.rb, spec/features/new_project_spec.rb, templates/Gemfile.erb, templates/dotfiles/.env, templates/rack_mini_profiler.rb
Uses [rack-mini-profiler][gem] gem to help debug slow queries /
requests.
Enable it by setting `ENV["RACK_MINI_PROFILER"] = 1`.
[gem]: https://github.com/MiniProfiler/rack-mini-profiler#rails
=> Generate `rack_mini_profiler`

templates/app.json.erb
https://github.com/thoughtbot/suspenders/commit/ca11a8638090d9f7b6af1ac55586d24d05c77df6
removed the dependency on `airbrake` in favor of `honeybadger`.
The `AIRBRAKE_API_KEY` was left in `app.json` but is no longer required.
This change removes it.
=> Removes AIRBRAKE_API_KEY as required env var

lib/suspenders/app_builder.rb, lib/suspenders/generators/app_generator.rb, templates/_css_overrides.html.erb, templates/suspenders_layout.html.erb.erb
CSS transitions often break tests. For example, a popup can take some
time to be fully shown if there is a transition time applied to its
show effect. The test will see that the popup is present and will try to
use it, but the element is ready yet.
This disables the CSS transitions in the test environment and removes
timing issues related to CSS.
=> Disable CSS transitions in tests

templates/Gemfile.erb
Prevent bundle audit check from passing when the vulnerability db is
out-of-date due to a failed update. This fix is intended to be temporary
until a fix is released for:
https://github.com/rubysec/bundler-audit/issues/114
=> Fix bundler-audit to exit on update failure

NEWS.md, README.md, lib/suspenders/adapters/heroku.rb, templates/app.json.erb, templates/rails_helper.rb
**DISCLAIMER:** I’m not sure if this is a good idea, just questioning the status quo
The proper way to access Rails' environment is through `Rails.env`,
which checks `RAILS_ENV`, falling back to `RACK_ENV`.
=> Remove `RAILS_ENV` declarations

NEWS.md, templates/browserslist
- According to http://caniuse.com/usage-table, global usage of IE 9 and 10 are
both around 0.6%.
=> Update browser support

lib/suspenders/app_builder.rb, spec/features/new_project_spec.rb
`:test` sends the emails to the logs, and to see them one has to scroll
back through them. If we configure delivery_method to be `:file`,
mails will also be created in the `./tmp/mails/` directory
One file will be created for each email address sent to that contains
all email content delivered to that address. This allows to easily
review any and all emails sent, without searching through logs.
See:
* https://github.com/thoughtbot/suspenders/pull/521 (https://github.com/thoughtbot/suspenders/commit/8b45fd42)
* http://blog.mojotech.com/a-decade-of-rails/
=> Set development delivery_method to :file

templates/_css_overrides.html.erb
- Remove webkit prefix
- This prefix hasn't been needed since Safari 6 and iOS Safari 6.1
- Reference: http://caniuse.com/#feat=css-transitions
=> Update CSS override

templates/Gemfile.erb
* Set Bourbon dependency to v5.0.0.beta.5, this should
resolve issues *ActionView::Template::Error: File to import not found
or unreadable: bourbon* that v5.0.0.beta.3 was causing
Please look at this issues for more info:
https://github.com/thoughtbot/suspenders/issues/727
=> Update Bourbon to v5.0.0.beta.5

NEWS.md, spec/features/heroku_spec.rb, templates/bin_deploy, templates/bin_setup_review_app.erb
I noticed that migrations were failing on my deploys but heroku was still registering it as a successful deploy. It turns out that `heroku run` does not return the status code from the command you want to run.
Adding `--exit-code` to the `heroku run` commands will correctly return the status code to the invoker.
Documentation: https://github.com/heroku/heroku-run
=> Return heroku run exit code status

NEWS.md, lib/suspenders/adapters/heroku.rb, lib/suspenders/app_builder.rb, lib/suspenders/generators/app_generator.rb, spec/features/new_project_spec.rb, templates/smtp.rb, templates/staging.rb
The only custom configuration of suspended apps for the staging
environment was the email interceptor, which can live in `production.rb`
and be configured through environmental variables.
* Simplifies configuration
* Enforces staging/production parity
* Follows Heroku recommendations (https://devcenter.heroku.com/articles/multiple-environments)
[fixes #506]
=> Drop staging environment file

spec/features/github_spec.rb, spec/features/heroku_spec.rb, spec/features/new_project_spec.rb, spec/support/suspenders.rb, suspenders.gemspec
Suspenders' tests generate an application to run assertions on it. This
means its runtime dependencies are themselves development dependencies.
Those dependencies were not being installed by suspenders' tests,
neither specified in its `.gemspec` as development dependencies, but
they were needed for new installation tests to run.
We address this issue by adding a `setup_app_dependencies` step in the
specs that need it, after generating an application (`run_suspenders`).
This ensures all dependencies are installed before we need them.
This makes it unnecessary to declare app dependencies in
`suspenders.gemspec`, because Rails and Bundler (only declared runtime
dependencies) will take care of those.
[fixes #732]
[fixes #739]
Pairing: @tute and @robskrob.
=> Fix suspenders development and runtime dependencies

suspenders.gemspec
@robskrob and I dropped that dependency in
ef3428e, but didn't notice that this is
not a generated app's dependency, and it's a suspenders dependency
instead. It should then be specified in the gemspec.
[fixes #748]
=> Bring back bitters development dependency

lib/suspenders/adapters/heroku.rb, lib/suspenders/app_builder.rb, lib/suspenders/generators/app_generator.rb, spec/adapters/heroku_spec.rb, spec/features/heroku_spec.rb
This sets the default application host to "[app-name]-[environment].herokuapp.com" to prevent the error I talked about in #746. 
Does this make sense? This configures the app to heroku defaults to make suspenders more plug & play, but still doesn't explain how to change this after acquiring a custom domain. Is a change even required in that case?
=> Set the default application host

lib/suspenders/app_builder.rb, lib/suspenders/generators/app_generator.rb, templates/disable_xml_params.rb
Vulnerabillity was fixed three years ago
(https://www.kb.cert.org/vuls/id/380039).
Also, this code doesn't work in Rails 5.
=> Drop initializer for disabling XML parser

NEWS.md, lib/suspenders/adapters/heroku.rb, lib/suspenders/app_builder.rb, lib/suspenders/generators/app_generator.rb, spec/adapters/heroku_spec.rb, spec/features/heroku_spec.rb, spec/features/new_project_spec.rb, templates/Gemfile.erb
This change makes new suspender apps "deployable to Heroku" by default,
moving the Heroku setup in the local machine to be run by default (i.e.
with the --heroku flag off). All the setup that requires to hit the
Heroku API to create the staging and production apps is kept to be run
only with the flag on.
=> Make new apps "deployable to Heroku" by default

NEWS.md, USAGE, lib/suspenders/generators/app_generator.rb, spec/features/cli_help_spec.rb, spec/support/suspenders.rb
This updates the command line output when you run `suspenders -h`.
Rather than receiving the rails usage and help messages, it will now provide instructions on how to use suspenders instead.
=> Provide suspenders-specific help output

NEWS.md, lib/suspenders/app_builder.rb, spec/features/new_project_spec.rb
`1.year.to_i` wasn't being parsed nor raising an error, failing silently
to add that line to the `production.rb` file.
=> Bugfix: configure static_cache_control in production

lib/suspenders/app_builder.rb, lib/suspenders/version.rb
* Use `configure_environment` helper in `app_builder.rb` file
* Drop comments from environment files that get trimmed anyway
* Freeze constants in `version.rb` file
* Delete unneeded `serve_static_files_line` method
* Drop trailing whitespace in NEWS
=> Many minor fixes

templates/suspenders_layout.html.erb.erb
- Add `width=device-width` to set the virtual viewport to the width of
the device's screen
- Add `shrink-to-fit=no` to tell Safari 9 not to shrink overflowing
content to fit the width of the virtual viewport
References:
- https://css-tricks.com/snippets/html/responsive-meta-tag/
- https://bitsofco.de/ios-safari-and-shrink-to-fit/
=> Update the viewport meta tag

lib/suspenders.rb, lib/suspenders/app_builder.rb, lib/suspenders/generators/app_generator.rb, lib/suspenders/generators/stylesheet_base_generator.rb, spec/features/new_project_spec.rb, templates/Gemfile.erb
This introduces the `suspenders:stylesheet_base` generator, which adds
our typical foundations for CSS. In this case it is Bourbon, Neat, and
Refills.
Of note, the `application.scss` must list the imports in a specific
order.
Paired with Justin Moore.
=> Introduce a stylesheet_base generator

lib/suspenders/app_builder.rb
`ENV["APPLICATION_HOST"]` is used before it's defined in the production
environment.
By using `inject_into_file` instead of `configure_environment` we can
control the order of the steps.
[fixes #776]
=> APPLICATION_HOST bug fix in production environment

lib/suspenders/generators/stylesheet_base_generator.rb
Neat 1.8 drops the Bourbon dependency.
=> Update Neat to 1.8.0

templates/app.json.erb
Heroku Review Apps can work well without this configuration set.
[closes #773]
=> WEB_CONCURRENCY isn't required in app.json

NEWS.md, README.md, lib/suspenders/adapters/heroku.rb, lib/suspenders/app_builder.rb, lib/suspenders/generators/app_generator.rb, lib/suspenders/version.rb, spec/features/new_project_spec.rb, templates/Gemfile.erb
Upgrade to Rails 5.0.0
* Replaces default Puma setup configuration that comes with Rails 5.
We were already using it as per Heroku preference.
* No need of static files custom logic
See https://blog.heroku.com/archives/2016/5/2/container_ready_rails_5
I needed to add the `listen` gem in development. See related PR to
Rails and its related issues: https://github.com/rails/rails/pull/24243
=> Upgrade to Rails 5.0.0

templates/Gemfile.erb
Refills is added to the Gemfile after install via the
`StylesheetBaseGenerator`. If it is also present in the Gemfile
template then bundler will issue a warning that refills is required
twice.
Changes:
- Remove refills from Gemfile template
=> Only require refills once

lib/suspenders/app_builder.rb, lib/suspenders/generators/app_generator.rb, lib/suspenders/generators/static_generator.rb, lib/suspenders/generators/stylesheet_base_generator.rb, spec/features/new_project_spec.rb
Static and Stylesheet suspenders' generators add gems to the `Gemfile`,
but don't run `bundle install` after the fact, making installations with
clean gem sets fail with errors like:
```
gemfile  high_voltage
generate  suspenders:stylesheet_base
Could not find gem 'high_voltage' in any of the gem sources listed in
your Gemfile or available on this machine.
Run `bundle install` to install missing gems.
run  bundle install
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies...
Using rake 11.2.2
```
By adding `bundle install` calls after modifying the `Gemfile` we ensure
each step will have the necessary dependencies for application code to
run.
[fixes #568]
[fixes …
=> Ensure stylesheet_base generator runs with a clean bundle

lib/suspenders/app_builder.rb, spec/features/new_project_spec.rb
In Rails 5, deploying to production environments will print a deprecation
warning when configuring config.static_cache_control. This changes the
configuration to use the new style config.public_file_server.headers.
=> Prefer using public_file_server.headers.

lib/suspenders/app_builder.rb, lib/suspenders/generators/app_generator.rb, spec/features/new_project_spec.rb
Suspenders doesn't use turbolinks by default. It doesn't include it in
the Gemfile, but the generated `application.js` was trying to include
it, resulting in a failure.
This fix make sure a newly generated application doesn't include
the turbolinks reference.
[fixes #788]
=> Remove turbolinks from application.js file

lib/suspenders/generators/app_generator.rb, spec/features/new_project_spec.rb
Before this change, new apps had both spec and test directories.
[fixes #798]
=> Bugfix: new applications generate only spec directory

lib/suspenders/generators/stylesheet_base_generator.rb
This matches how we specify the Bourbon dependency in Bitters and means
we won't have to coordinate releases between the two so closely.
Fixes https://github.com/thoughtbot/suspenders/issues/805
=> Specify Bourbon version pessimistically

NEWS.md, suspenders.gemspec
We just cut the `1.5` release of Bitters, which continues the work found in https://github.com/thoughtbot/suspenders/pull/806.
Bitters `1.5` change log:
**Changed**
- Updated Bourbon dependency to 5.0.0.beta.7.
Once we merge this, I recommend we cut a `1.43.0` of Suspenders to release these fixes from the Bourbon/Bitters issues.
=> Update Bitters to 1.5

spec/features/new_project_spec.rb
I noticed that line 122 creates a file named `production_config.rb` in the repo root path when you run `rspec spec` on my dev machine. I think the line might be a leftover from a previous commit. Am I right?
=> Do not create test file in repo root folder

lib/suspenders/app_builder.rb
If I run `rails g scaffold post title:string`, I got a warning about javascript-engine
```bash
↳ $ rails g scaffold post title:string
Running via Spring preloader in process 18853
invoke  active_record
create    db/migrate/20161219223207_create_posts.rb
create    app/models/post.rb
invoke    rspec
create      spec/models/post_spec.rb
invoke      factory_girl
insert        spec/factories.rb
invoke  resource_route
route    resources :posts
invoke  scaffold_controller
create    app/controllers/posts_controller.rb
invoke    erb
create      app/views/posts
create      app/views/posts/index.html.erb
create      app/views/posts/edit.html.erb
create      app/views/posts/show.html.erb
create      app/views/posts/new.html.erb
create      app/views/posts/_form.html.erb
invoke    rspec
create …
```
=> Fix generators config: remove warning when scaffolding

README.md
No longer needed in Rails 5: https://github.com/heroku/rails_12factor#rails-5
=> Remove 12factor gem component for logging

spec/features/new_project_spec.rb, templates/Gemfile.erb
No longer needed since Rails 5 includes Heroku's 12factor methodology
=> Remove rails_stdout_logging gem

lib/suspenders/adapters/heroku.rb
As requested by @nickcharlton [here](https://github.com/thoughtbot/administrate/pull/578#issuecomment-274091479). I couldn't run the tests locally since I get this error:
```
Bundler::GemNotFound: Could not find gem 'simple_form' in any of the gem sources listed in your Gemfile.
/home/deivid/.gem/ruby/2.4.0/gems/bundler-1.14.0.pre.2/lib/bundler/resolver.rb:376:in `block in verify_gemfile_dependencies_are_found!'
/home/deivid/.gem/ruby/2.4.0/gems/bundler-1.14.0.pre.2/lib/bundler/resolver.rb:346:in `each'
/home/deivid/.gem/ruby/2.4.0/gems/bundler-1.14.0.pre.2/lib/bundler/resolver.rb:346:in `verify_gemfile_dependencies_are_found!'
/home/deivid/.gem/ruby/2.4.0/gems/bundler-1.14.0.pre.2/lib/bundler/resolver.rb:201:in `start'
/home/deivid/.gem/ruby/2.4.0/gems/bundler-1.14.0.pre.2/lib/bundler/res …
```
=> Use an sh-compatible construct

lib/suspenders/app_builder.rb
Replace `$`with `%` (as the latter is used in the main README template) in order to improve consistency in the generated README. Currently, both symbols are used to indicate terminal commands, leading to this silliness:
Of course, this is far from a big deal – but I'm a man who prefers consistency, and I'm betting you are too.
=> Change terminal symbol in README's deploying section

lib/suspenders/app_builder.rb, spec/features/new_project_spec.rb, templates/bundler_audit.rake
Instead of defining the audit task from scratch, we can now import the task from the gem itself.
One caveat: The task name changes from `bundler:audit` to `bundle:audit` as defined by the gem. We could make an alias between the old & new command but I suspect most use is just via the default Rake task.
=> Use bundle-audit rake task from the gem

README.md, lib/suspenders/adapters/heroku.rb, lib/suspenders/app_builder.rb, lib/suspenders/generators/app_generator.rb, spec/adapters/heroku_spec.rb, templates/bin_setup_review_app.erb
When a PR Review environment is created, the latest backup is currently used. If no backups exist, or if the backup is old and outdated, recent data used for testing may not exist.
This forcibly creates a backup right before migration -- leading to the most recent data.
Another way to solve this would be to automatically add `pg:backups:schedule` on all staging environments on original app scaffolding, but that would be up to 24 hours difference.
=> Schedule Heroku Backups and Capture backup of existing staging database for Review Apps

lib/suspenders/generators/app_generator.rb, spec/support/suspenders.rb
The tests had started printing git error messages:
```
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
```
These were coming from three places:
- `suspenders.gemspec`, which collects all `Gem::Specification#files=`
by shelling out to `git ls-files`.
- `suspenders.gemspec`, which collects all
`Gem::Specification#test_files=` by shelling out to
`git ls-files -- {test,spec,features}/*`.
- Honeybadger, which figures out which revision to tag the error with by
invoking `rev-parse`:
def from_git
return nil unless File.directory?('.git')
`git rev-parse HEAD`.strip rescue nil
end
Although I am unsure why these things started to matter now, I found two
changes that improve the situation:
- In the test suite, make an initial commit after suspender'ing a
project. …
=> Fix fatal git failures in tests

spec/features/new_project_spec.rb, templates/spec_helper.rb
Safe mode forces you to use Timecop with the block syntax, which
always puts time back the way it was beforehand.
https://github.com/travisjeffery/timecop#timecopsafe_mode
This prevents accidentally writing tests where time is frozen but not reset to real time afterwards, which is a source of order dependent test failures.
=> Configure TimeCop safe mode

README.md
Seems this was pointed to the wrong repo in a236ae4bb3d8c7f4858a36e13a00ca3244bf4a97.
=> Fix incorrect Timecop link

lib/suspenders.rb, lib/suspenders/actions.rb, lib/suspenders/app_builder.rb, lib/suspenders/generators/app_generator.rb, lib/suspenders/generators/enforce_ssl_generator.rb, spec/features/new_project_spec.rb
This setting has been on for every thoughtbot Rails app I've touched
in the past year or two (maybe a dozen?).
* Use `configure_environment` helper method more consistently.
* Fixes https://github.com/thoughtbot/suspenders/issues/781
More about the pervasiveness of SSL in our ecosystem:
https://blog.heroku.com/announcing_heroku_free_ssl_beta_and_flexible_dyno_hours
https://letsencrypt.org/
=> Enforce SSL in production environment

NEWS.md, templates/bin_setup
The idea behind the .git/safe is that I run it manually and explicitly
after I trust the directoy and the team behind the project.
Creating it as part of the setup script defeats the point of that. Doing
so without explcitly telling the user comes across as sneaky, perhaps.
(I do expect all devs to read setup scripts before running them -- but I
also know that they do not!)
Switch this script to inform the user that they have no `.git/safe`
directory but might like to make one.
=> .git/safe is opt-in

lib/suspenders.rb, lib/suspenders/generators/app_generator.rb, lib/suspenders/generators/initialize_active_job_generator.rb, spec/features/new_project_spec.rb, templates/active_job.rb
`ActiveJob` attaches a single `LogSubscriber` to be notified of events.
When one job enqueues another, that's treated as a child event and
stored on the same stack as the parent. If a large number of children
are enqueued that leads to R14 errors on Heroku.
The fix here is to unsubscribe all existing "enqueue" listeners and
then add a new subscriber for just that event. The original handler
is copied from the parent class using `define_method` so that it's
picked up by `attach_to`.
Related:
https://github.com/rails/rails/issues/21036
https://github.com/rails/rails/pull/5932
Before and after:
🎩  tip @trevororeilly
=> Prevent memory bloat in ActiveJob children

README.md, templates/Gemfile.erb, templates/postgresql_database.yml.erb, templates/secrets.yml
The staging environment is set to production as of
ffa20dbeec382d6a78704be15881d5dd1248d9df in order to:
* Simplify configuration
* Enforce staging/production parity
* Follow Heroku recommendations
https://devcenter.heroku.com/articles/multiple-environments
For Honeybadger, we set a config variable `HONEYBADGER_ENV=staging`.
Related:
https://github.com/thoughtbot/suspenders/pull/743
=> Remove vestigial `staging` references

lib/suspenders/actions.rb, lib/suspenders/app_builder.rb, spec/features/new_project_spec.rb
This PR fixes a problem introduced in https://github.com/thoughtbot/suspenders/pull/853 and regarding https://github.com/thoughtbot/suspenders/issues/843.
`config.action_mailer.asset_host` accepts a plain string, not an hash like its cousin `config.action_mailer.default_url_options` does.
Plus, I had to add the protocol (`http` for `development` and `test`). Rails would not add the protocol for you and so if you have a logo in your email its url would be something like `//localhost:3000/assets/logo.png`. If you open the email in your native mail client, for instance, it won't load the image. This is why I had to specificy `http:` for `asset_host`.
How to manage this protocol problem in production? In my last application, I defined an `ASSET_HOST` env variable to be like my …
=> Fix for action mailer asset_host: it should be a string, not an hash

CONTRIBUTING.md
This comes up far too often when popping in to work on this project, so
document what to do when it happens.
=> Document Bundler::RubyVersionMismatch

lib/suspenders.rb, lib/suspenders/app_builder.rb, lib/suspenders/generators/app_generator.rb, lib/suspenders/generators/ci_generator.rb, templates/spec_helper.rb
This introduces the `suspenders:ci` generator, which sets us up with a
continuous integration configuration. In this case, Circle CI 1.0.
This is 1.0 and not 2.0 because this is a refactoring, not a feature
change.
Move the Heroku configuration to the end so that we can be sure that
`circle.yml` exists by the time it runs.
---
This is a continuation from #511, in which we decided that all parts of Suspenders should move into generators. The battle is long but we will get this.
This is inspired by #844, which presents a solution that is orthogonal to our long-term goals set from #511. This replaces #844 (or certainly redefines it).
=> Introduce a CI generator

NEWS.md, lib/suspenders/version.rb
This PR bumps the gem version to 1.46.0 with the following changes:
* Bug fix: Fix for action mailer asset_host
* Bug fix: Lock pg to ~> 0.18
* Breaking: Remove Database Cleaner
* Upgrade: Update to Rails 5.1.4
* Upgrade: Update to Ruby 2.5.0
* Upgrade: Update bourbon from 5.0.0.beta.8 to 5.0.0
* Upgrade: Update FactoryGirl to FactoryBot
* Generators: Analytics generator
* Generators: CI generator
* Generators: DB optimization generator
* Generators: Factories generator
* Generators: Forms generator
* Generators: Javascript driver generator
* Generators: Jobs generator
* Generators: Lint generator
* Generators: Testing driver generator
* Generators: Views generator
=> Bump to version 1.46.0

spec/features/new_project_spec.rb, templates/application.scss
When an `@import` in Sass ends with `.css`, Sass doesn't pull that file
in as a partial and concatenate those styles with the rest of the
manifest. Rather, it outputs a CSS `@import`, which we don't want here.
=> Fix normalize.css Sass import

lib/suspenders/app_builder.rb, lib/suspenders/generators/app_generator.rb, lib/suspenders/generators/production/email_generator.rb, spec/features/new_project_spec.rb, templates/email.rb, templates/smtp.rb
This introduces `suspenders:production:email`, a generator that installs
our email settings for production. In this case it sets up SMTP with
variables based on environment variables.
I separated out the RecipientInterceptor configuration, since that is a
development- and testing-related configuration.
=> Introduce an email generator

spec/support/suspenders.rb, templates/Gemfile.erb
The suspenders gem brings in additional dependencies, not all of which
are needed in production. We only need suspenders during development --
it's a collection of Rake tasks for improving our dev speed, afterall --
so move it to the development group.
Closes #890, #891.
---
Mostly opening this for CI. I'm going to merge it without review, unless someone sneaks in.
=> Move suspenders to development group of Gemfile

lib/suspenders/app_builder.rb, spec/features/api_spec.rb
When running `suspenders --api`, there are some missing files in the
generated API-only Rails app compared to the non-API version, which
causes the suspenders generator to crash.
To fix this, just don't do anything when those files aren't found.
* There are no HTTP error pages, so `customize_error_pages` fails
* `config/initializers/assets.rb` is removed by the API generator, leading to this error:
```
Setting up the production environment
create  config/smtp.rb
prepend  config/environments/production.rb
insert  config/environments/production.rb
append  config/environments/production.rb
insert  config/environments/production.rb
insert  config/environments/production.rb
Traceback (most recent call last):
25: from /Users/gabe/.rbenv/versions/2.5.0/bin/suspenders:23:in `<main>'
24: from …
```
=> Let `suspenders --api` work

.travis.yml, lib/suspenders/generators/app_generator.rb, suspenders.gemspec
- Ruby upgrade, in which I learn that there are at least two additional
dev dependencies because of the nature of the beast.
- Silence simple_form when the --api flag is passed, thanks to a test
introduced in #902.
- Manually install bundler on Travis due to an [incompatibility] within a
smattering of tools.
[incompatibility]: https://github.com/travis-ci/travis-ci/issues/9333
=> A few things around tests

README.md
To prevent MITM attacks and to follow general best practices, change the `hub` url from `http://hub.github.com/standalone` to `https://hub.github.com/standalone`
=> Use HTTPS url for Github Hub script

lib/suspenders/actions.rb, lib/suspenders/generators/app_generator.rb, lib/suspenders/generators/production/email_generator.rb, spec/features/new_project_spec.rb, spec/features/production/email_spec.rb, spec/support/contain_json_matcher.rb, spec/support/exist_as_a_file_matcher.rb, spec/support/suspenders.rb, templates/app.json.erb
The `SMTP_ADDRESS`, `SMTP_DOMAIN`, `SMTP_PASSWORD`, and `SMTP_USERNAME`
variables are only required when dealing with emails in production, so
reflect that in our `app.json` and the `suspenders:production:email`
generator.
This introduces our first test for destroying a generator. It also
introduces some awesome code for un-merging a Hash from another Hash.
The Heroku actions create the `app.json`, so make sure they run before
we modify it. It makes sense to run all production generators after the
Heroku-specific actions, so make that clumping happen.
=> suspenders:production:email can control app.json

NEWS.md, lib/suspenders/generators/production/timeout_generator.rb
Resolves #918
Rack::Timeout v0.5.0 removed legacy setter methods used for
configuration (https://github.com/heroku/rack-timeout/pull/125) such
that the configuration added by Suspenders causes a NoMethodError when
initializing Rails in the production environment (e.g. during Heroku
deployment). This PR switches to using environment variable-based
configuration of Rack::Timeout, matching the recommendations in the
README.
=> Switch to ENV configuration of Rack::Timeout

templates/bin_setup
This gets run when first creating a Suspenders project but not on setup. It should be.
=> We need to install JS dependencies in setup

lib/suspenders/app_builder.rb
Related to #933 - The Open Directory Project has closed down.
=> Remove noodp robots meta tag from error pages

lib/suspenders/generators/production/email_generator.rb
The email generator attempts to inject SMTP config into `config/environments/production.rb` after the line `config.action_mailer.raise_delivery_errors = false`. This line is not found anymore and thus fails (NB: find reference).
I propose the code is injected after `config.action_mailer.perform_caching = false` instead.
In production, you may experience the following error as action mailer attempts to use the default port 25:
```
Connection refused - connect(2) for "localhost" port 25
/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/net/smtp.rb:539:in `initialize'
/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/net/smtp.rb:539:in `open'
/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/net/smtp.rb:539:in `tcp_socket'
/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/net/smtp.rb:549:in `block in do_start' …
```
=> Fix email generator

lib/suspenders/generators/app_generator.rb
With e09a56d we are getting a failing spec because of an extra newline
in the production config. Removing comments later will take care of the
extra newlines, and I think may have made e09a56d unnecessary.
=> Strip extra newline from the production config

README.md, templates/Gemfile.erb, templates/_javascript.html.erb
Rails dropped jQuery as a dependency back in
https://github.com/rails/rails/pull/27113. That commit removed
'jquery-ujs' from the application.js and replaced it with 'rails-ujs'.
Since we aren't using 'jquery-ujs', we don't need the 'jquery-rails'
gem.
As for the test JS, `$.fx.off = true` shouldn't be necessary if
we aren't using jQuery, and `$.ajaxSetup({ async: false });` seems
to have been for Akephalos, which we no longer use.
For your amusement: https://robots.thoughtbot.com/thoughtbot-and-the-holy-grail
=> Drop jquery-rails gem

lib/suspenders/app_builder.rb, lib/suspenders/generators/app_generator.rb
The ASSET_HOST environment variable needs to be set correctly on Heroku review apps. Before this change the review app check was happening *after* the setting of the asset host and consequently assets weren't loading.
This moves the review app check to the top of the config file so the ASSET_HOST gets set correctly on review apps.
=> Move the review app check before asset host

templates/factory_bot_rspec.rb
Setting `FactoryBot.use_parent_strategy = true` allows objects made with
the build strategy to use `build` instead of `create` for any
associations. Using this setting will generally reduce the number of
calls to `create`, and makes `build` generally
[a little faster](https://gist.github.com/composerinteralia/d4796df9140f431e36f88dfb6fe9733a) than `build_stubbed`.
=> Use parent strategy for factories

lib/suspenders/generators/stylesheet_base_generator.rb
To merge #936, we need to make sure we have a version of bourbon with
https://github.com/thoughtbot/bourbon/commit/8257c683f8a250c06407f66d077dfbe6ce6595b0
and a version of neat with
https://github.com/thoughtbot/neat/commit/a092ff79a5f81be5a01328f9daa5e15f97b4a58a
I also got rid of the pessimistic version constraint so a fresh
suspenders run will always give us the latest versions of these gems.
=> Use sassc-compatible versions of neat and bourbon

.travis.yml
Bundler 2.0.1 works with Rails, but [the released version of
bundler-audit hardcodes a dependency on 1.x]. [Downgrade Bundler on Travis]
until [the new bundler-audit] is out.
[the released version of bundler-audit hardcodes a dependency on 1.x]: https://github.com/rubysec/bundler-audit/issues/202
[Downgrade Bundler on Travis]: https://docs.travis-ci.com/user/languages/ruby/#bundler-20
[the new bundler-audit]: https://github.com/rubysec/bundler-audit/pull/203
=> Downgrade Bundler on Travis

lib/suspenders/generators/analytics_generator.rb, lib/suspenders/generators/base.rb, lib/suspenders/generators/ci_generator.rb, lib/suspenders/generators/db_optimizations_generator.rb, lib/suspenders/generators/factories_generator.rb, lib/suspenders/generators/forms_generator.rb, lib/suspenders/generators/jobs_generator.rb, lib/suspenders/generators/js_driver_generator.rb, lib/suspenders/generators/json_generator.rb, lib/suspenders/generators/lint_generator.rb, lib/suspenders/generators/production/deployment_generator.rb, lib/suspenders/generators/production/email_generator.rb, lib/suspenders/generators/production/force_tls_generator.rb, lib/suspenders/generators/production/manifest_generator.rb, lib/suspenders/generators/production/timeout_generator.rb, lib/suspenders/generators/staging/pull_requests_generator.rb, lib/suspenders/generators/static_generator.rb, lib/suspenders/generators/stylesheet_base_generator.rb, lib/suspenders/generators/testing_generator.rb, lib/suspenders/generators/views_generator.rb
We keep repeating the same code; time to extract it into a shared
object. Since Thor pulls us into inheritance, use a superclass.
This superclass includes our custom actions, defines an app name, and
sets the source root. I could not figure out how to use the
`source_root` class method; since we're inheriting from the
Rails::Generators::Base we can override the `default_source_root` class
method instead to achieve the same effect.
=> Suspenders::Generators::Base base class

templates/Gemfile.erb
spec/features/api_spec.rb is failing on CI because Rails 5.2.3 in API
mode isn't playing well with autoprefixer-rails. It doesn't really make
sense to have a gem for CSS in API mode.
=> Avoid installing autoprefixer in api mode

lib/suspenders/generators/testing_generator.rb, templates/rails_helper.rb
RSpec [suggests using system tests over feature specs][rspec]. Starting
a new project with suspenders I was surprised that I did not have access
to the Formulaic::Dsl available in my system specs.
This commit replaces the old feature spec setup with an equivalent
system spec setup, allowing system tests to have access to the
Formulaic::Dsl
[rspec]: https://rspec.info/blog/2017/10/rspec-3-7-has-been-released/#rails-actiondispatchsystemtest-integration-system-specs
=> Replace feature specs with system specs

lib/suspenders/generators/js_driver_generator.rb, templates/capybara_silence_puma.rb
When Capybara starts the first JavaScript spec of a run, it starts Puma
and prints out the Puma startup messages:
Capybara starting Puma...
* Version 3.12.1 , codename: Llamas in Pajamas
* Min threads: 0, max threads: 4
* Listening on tcp://127.0.0.1:62516
By setting `Silent: true`, we can prevent those messages from being printed.
A bit of background: https://github.com/rspec/rspec-rails/issues/1897
Proof that Capybara uses Puma as its default server: https://github.com/teamcapybara/capybara/blob/3.24.0/lib/capybara.rb#L247-L249
=> Silence Puma's startup messages in JS specs

templates/chromedriver.rb
When I use Suspenders' configuration on a new project, JavaScript tests open up the Chrome app in a real window (i.e. not headless).
When using the configuration in this commit, Chrome quietly bounces once, in the taskbar (on macOS), and does not create a window.
=> Make Chromedriver truly headless

templates/chromedriver.rb
1680x1050 is the size of a 15" retina Macbook Pro.
Without this setting, `save_and_open_screenshot` captures perhaps 75% of the screen, which makes it much less useful for debugging.
I'm sure some people have bigger screens, and could use an even larger window size, but this feels like a good default.
=> Set a bigger window for `save_and_open_screenshot`

spec/features/staging/pull_requests_spec.rb
https://github.com/thoughtbot/suspenders/pull/956 introduced the `:generator` type.
This fixes a typo in the type name.
=> Fixes typo in example group type

README.md, docs/heroku_deploy.md
I think that the process of deploying to Heroku has created enough [confusion](https://github.com/thoughtbot/suspenders/issues/935) and [frustration](https://github.com/thoughtbot/suspenders/issues/919#issuecomment-421632156) that it's time to add a simple summary of the setup required to the documentation about it. This should be updated and expanded or contracted when new issues arise or are resolved.
=> Add documentation for Deploying to Heroku to README

.travis.yml, lib/suspenders/generators/app_generator.rb, lib/suspenders/version.rb, spec/features/new_project_spec.rb, suspenders.gemspec, templates/Gemfile.erb, templates/_javascript.html.erb, templates/dotfiles/.env
In addition to bumping the Rails version, this commit makes a couple JS
changes to support Rails using webpacker by default.
The remaining changes were to get CI to pass:
- Explicitly adding the travis postgresql service might not have solved
the test failures I was having, but it did make some warnings go away.
- I don't fully understand why we need to add rack_timeout as a
development dependency and not any of the other gems, but it made Travis
happy
- I also don't fully understand why I needed to move the
`suspenders:views` generator last. The tests passed locally without
that change, and I was able to generate a working application regardless
of the order. But on CI, the generators that ran just after
`suspenders:views` were failing with errors about `flashes_helper.rb`
not existing. …
=> Bump Rails version to 6.0.0

lib/suspenders/generators/base.rb
```
DEPRECATION WARNING: `Module#parent_name` has been renamed to
`module_parent_name`. `parent_name` is deprecated and will be removed in
Rails 6.1.
```
=> Address deprecated method name

lib/suspenders/app_builder.rb, templates/browserslist
Fixes #993
Webpacker already generates `.browserslistrc`, which is not compatible
with `browserslist`. I decided to go with the default options provided
by the [webpacker `.browserslistrc`][browserslistrc], rather than trying
to override it with our own, to minimize maintenance in suspenders as
more browsers become unused.
[browserslistrc]: https://github.com/rails/webpacker/blob/master/lib/install/config/.browserslistrc
=> Remove browserslist

.travis.yml
a0b8511ed downgraded bundler because bundler-audit had a pessimistic
constraint on bundler. bundler-audit has since released a version that
works with bundler 2.
=> Use the latest version of bundler

templates/Gemfile.erb
Closes #950
Back in 2014 the [spring listen watcher was extracted into a gem][b614].
Since that time, the listen gem has been in our Gemfile not doing
anything. Both spring and listen are dependencies of
spring-watcher-listen, so we can replace them both.
[b614]: https://github.com/rails/spring/commit/b614d94e83d863ffcb3eec06c6b2bb9250d5b5a5
=> Use spring-watcher-listen gem

lib/suspenders/app_builder.rb, lib/suspenders/generators/production/manifest_generator.rb, templates/bin_auto_migrate, templates/bin_deploy, templates/bin_setup_review_app.erb
Heroku's [Release Phase](https://devcenter.heroku.com/articles/release-phase) feature provides a much better migration experience for a production deploy of a Rails application.
Without using a release phase task, here's how you migrate your database
in production:
1. Deploy your application via Git or pipeline promotion.
2. With the migration deployed, run `rake db:migrate`.
3. Immediately restart the application so that Rails is now aware of the
schema changes.
This process is awkward and can lengthen downtime in deploys. It results
in the application being restarted twice (once for the deployment of
code, and then again post-migration), and also may push application
logic that depends on the new code into production before the migration
has run or finished, which can lead to …
=> Use Release Phase for database migration

templates/rails_helper.rb
Suspenders was checking for the presence of `DATABASE_URL` to see if it
was running in production. This isn't so reliable in practice as
`DATABASE_URL` can be used in other environments. The spirit of this was
originally to stop you truncating a production database, which checking
for the Rails environment acheives.
https://github.com/thoughtbot/suspenders/issues/872
https://github.com/rspec/rspec-rails/pull/1383
=> Check for the environment, not DATABASE_URL

templates/Gemfile.erb
This commit should fix the CI on master.
I don't know if in thoughtbot you already use sprockets v4. We do not, so we fixed the version of sprockets to v3. Even Rails 6 does not support sprockets v4 right now 🤔 
From a plain new `rails new blog` application with rails 6
```
sass-rails (5.1.0)
railties (>= 5.2.0)
sass (~> 3.1)
sprockets (>= 2.8, < 4.0)
sprockets-rails (>= 2.0, < 4.0)
tilt (>= 1.1, < 3)
```
=> Keep using sprockets v3

spec/features/heroku_spec.rb, spec/features/new_project_spec.rb, spec/features/production/manifest_spec.rb, spec/support/contain_json_matcher.rb
We have two variety of fixes here: Heroku migration, and JSON subset
matcher.
The Heroku migration improvements from 5b68a176cbd40456e80ea9b91a98597cd91b4d8d
modified the `circle.yml` and `bin/deploy` files, but three tests had
not caught up.The `circle.yml` checks can be removed; that's no longer
done. Any reference to `heroku run rails db:migrate` can be removed;
that's handled for us automatically.
The `contain_json` matcher used `Hash#<=` to find the sub-hash; however,
this does not recur. Instead we can write our own recursive `subhash?`
helper method.
=> Fix failing tests

NEWS.md, lib/suspenders/adapters/heroku.rb, spec/adapters/heroku_spec.rb, spec/features/heroku_spec.rb
Adding a local remote for the Heroku environments with `heroku join`
consistently fails. In the time since this line was first introduced,
the semantics of the CLI's heroku join call might have changed.
Since this line serves as a guard to ensure that the local machine has
proper access to the Heroku application, replace `heroku join` with
`heroku apps:info` to check for whether or not the command line has
access to the deployment's metadata.
Since we're interested in the exit code of `heroku apps:info` and not
the content, pipe the output to `/dev/null`.
=> `bin/setup`: Join with `heroku apps:info`

lib/suspenders/generators/production/timeout_generator.rb, suspenders.gemspec
Travis was complaining about missing `rack-timeout` gem because, even if
we defined the `rack-timeout` as a `production` only gem, when we run
`bundle install` we install all of the gems, regardless of the
environment.
I added the `bundle install` command in the timeout generator, so this
should remove the need of a dev dependency on `rack-timeout`
=> Remove unnecessary dev dependency

docs/heroku_deploy.md, lib/suspenders/adapters/heroku.rb, lib/suspenders/app_builder.rb, lib/suspenders/generators/app_generator.rb, spec/adapters/heroku_spec.rb
We can automatically add buildpacks to heroku! :)
```
Buildpack added. Next release on provaprova-staging will use heroku/nodejs.
Run git push staging master to create a new release using this buildpack.
run  heroku buildpacks:add --index 2 heroku/ruby --remote staging from "."
Buildpack added. Next release on provaprova-staging will use:
1. heroku/nodejs
2. heroku/ruby
Run git push staging master to create a new release using these buildpacks.
run  heroku buildpacks:add --index 1 heroku/nodejs --remote production from "."
Buildpack added. Next release on provaprova-production will use heroku/nodejs.
Run git push production master to create a new release using this buildpack.
run  heroku buildpacks:add --index 2 heroku/ruby --remote production from "."
Buildpack added. Next release on …
```
=> Automatically configure buildpacks on heroku

docs/heroku_deploy.md, lib/suspenders/app_builder.rb, lib/suspenders/generators/production/manifest_generator.rb, spec/features/production/manifest_spec.rb
I noticed that `bin_auto_migrate` was not copied into project directory. I think it must be present so heroku will call it in its `release` script
=> Copy auto migrate into project

templates/chromedriver.rb
According to the documentation from [`rspec-rails`][rspec-rails]:
> RSpec **does not** use your `ApplicationSystemTestCase` helper.
> Instead it uses the default `driven_by(:selenium)` from Rails. If you
> want to override this behaviour you can call `driven_by` manually in a
> test.
This commit introduces an [`RSpec.configure`][configure] block which
sets the default driver for `type: :system` tests by invoking
[`driven_by`][driven_by] with [`:rack_test`][rack_test].
To opt into JavaScript-enabled tests, set the `js: true` (or `:js`)
metadata on a `describe`, `context`, or `it` block.
[driven_by]: https://api.rubyonrails.org/v6.0/classes/ActionDispatch/SystemTestCase.html#method-c-driven_by
[rspec-rails]: https://relishapp.com/rspec/rspec-rails/v/3-9/docs/system-specs/system-spec …
=> Configure System Test drivers with `driven_by`

.travis.yml
The tzinfo-data gem is only used by MS Windows and JRuby. This causes
Bundler to print a warning on actual OSes used for development or for
hosting.
> The dependency tzinfo-data (>= 0) will be unused by any of the
> platforms Bundler is installing for. Bundler is installing for ruby
> but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32,
> java. To add those platforms to the bundle, run `bundle lock
> --add-platform x86-mingw32 x64-mingw32 x86-mswin32 java`.
Silence this warning in CI with the `disable_platform_warnings` Bundler
configuration, [documented] to
> Disable warnings during bundle install when a dependency is unused on
> the current platform.
[documented]: https://bundler.io/v1.17/bundle_config.html
=> Disable platform warnings in CI

spec/features/new_project_spec.rb, templates/dotfiles/.ctags
Not all of us are blessed with ctags-compatible editors these days, but
that's not the main thing.
Those of us who are using an editor built for programming are [running
ctags automatically], and therefore the configuration in `.ctags` is not
useful.
[running ctags automatically]: https://github.com/ludovicchabant/vim-gutentags/
Of the projects I found on my laptop, none have modified `.ctags` beyond
this default.
This file made more sense [when it was added], but now it's a relic of a
different era.
[when it was added]: https://github.com/thoughtbot/suspenders/pull/595
=> Remove .ctags configuration

lib/suspenders/app_builder.rb, lib/suspenders/generators/app_generator.rb, lib/suspenders/generators/base.rb, lib/suspenders/generators/static_generator.rb, lib/suspenders/generators/testing_generator.rb, spec/features/static_spec.rb
We had a part of the code that made placeholder directories. Let's
remove most of them and move the rest around.
The `app/views/pages` directory is used for static pages as used by
`high_voltage`. Move that into the `StaticGenerator`.
The `spec/support` directory is used for all tests, and implied by
creating subdirectories. The `TestingGenerator` does this for us.
This removes `spec/lib`, `spec/controllers`, `spec/helpers`,
`spec/support/matchers`, `spec/support/mixins`, and
`spec/support/shared_examples`.
The `spec/lib` and `spec/helpers` directories are for tests under `lib`
and `app/helpers`, respectively. These directories are rarely used these
days, so let's not make these directories by default.
The `spec/controllers` directory is for controller unit tests. These
have mostly been …
=> Shuffle custom placeholder directories

lib/suspenders/app_builder.rb, lib/suspenders/generators/app_generator.rb
This did three things:
- Specify the charset in the HTML body.
- Specify the viewport.
- Remove comments.
The charset was removed from Rails in
https://github.com/rails/rails/commit/38f669766cb4d328e121afab020f4a52ca45421f .
It's not needed in the HTML if it's sent from the server. It's best to
send it from the server, in fact; otherwise the browser will parse the
first _n_ bytes of the file in a default charset, hit the charset meta
tag, then re-parse from the top under the new charset. We can remove
this meta tag now.
The viewport is in the default error page HTML as of
https://github.com/rails/rails/commit/7166507eae3d12c22e04a99ddd70972419643cd3 .
That leaves us with the comments. It'd be nice if they weren't there. I
don't know if that's worth a generator. The comment reads e.g.
``` …
```
=> Stop customizing error pages

.travis.yml, spec/support/suspenders.rb
If we change the value of `$HOME`, that means git(1) might not know who
we are. That can lead to warnings like this (taken from CI):
```
*** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: unable to auto-detect email address (got 'travis@travis-job-da8e5dbd-8be0-4778-931d-583b72258a58.(none)')
```
Let's set our name and email whenever we run commands under a different
home directory, just to be tidy.
=> Identify ourselves to git when changing HOME

lib/suspenders/generators/base.rb, lib/suspenders/generators/ci_generator.rb, lib/suspenders/generators/db_optimizations_generator.rb, lib/suspenders/generators/production/deployment_generator.rb, lib/suspenders/generators/production/email_generator.rb, lib/suspenders/generators/profiler_generator.rb, lib/suspenders/generators/runner_generator.rb, lib/suspenders/generators/staging/pull_requests_generator.rb, spec/features/ci_spec.rb, spec/features/db_optimizations_spec.rb, spec/features/runner_spec.rb, spec/support/project_files.rb, templates/Gemfile.erb, templates/partials/ci_simplecov.rb, templates/partials/db_optimizations_configuration.rb, templates/partials/deployment_readme.md, templates/partials/email_smtp.rb, templates/partials/profiler_readme.md, templates/partials/pull_requests_config.rb, templates/partials/runner_readme.md, templates/partials/runner_setup.rb, templates/spec_helper.rb
This adds a `templates/partials` directory, for storing incomplete
templates. They are named after their generator; for example, the
`runner` generator has templates `runner_readme.md` and
`runner_setup.rb`.
Extract all the heredoc into these templates. This gives us an easier
view into the content and more access to syntax highlighting in more
places (e.g. GitHub).
Along the way, backfill tests for generators without any: `ci` and
`db_optimizations. This exposed an issue with the `ci` generator: it did
not work with the default Rails `test/test_helper.rb`, and it mixed
SimpleCov in various places. So this is a substantial change to that
one generator.
---
[Idea](https://github.com/thoughtbot/suspenders/pull/1019#discussion_r354010635) by @jsilasbailey .
=> Move heredoc into templates

.travis.yml, spec/support/rails_template.rb, spec/support/suspenders.rb
We are seeing failures on CI for `Bundler could not find compatible
versions for gem "thor"`.
When our tests run `rails new`, that bundle installs inside the new
Rails application with thor constrained to ">= 0.20.3", "<2.0".
This started resolving to thor 1.0.0 when that version came out last
December (which is when our test suite started failing).
2019.
After running rails new, we add suspenders to the Gemfile of the new
rails application. suspenders depends on bitters, which depends on thor
"~> 0.19". This is incompatible with thor 1.0.0, which by this point is
already in the Gemfile.lock
This commit gets around the problem by adding suspenders to the Gemfile
via a template so it is there before the `bundle install`
=> Add suspenders to rails app earlier

lib/suspenders/generators/advisories_generator.rb, suspenders.gemspec
The most important part of this Bitters release is the updated
dependency on Thor. We were seeing issues like:
```
Bundler could not find compatible versions for gem "thor":
In snapshot (Gemfile.lock):
thor (= 1.0.1)
In Gemfile:
suspenders was resolved to 1.53.0, which depends on
bitters (~> 2.0) was resolved to 2.0.3, which depends on
thor (~> 0.19)
rails (~> 6.0.2, >= 6.0.2.1) was resolved to 6.0.2.1, which depends on
railties (= 6.0.2.1) was resolved to 6.0.2.1, which depends on
thor (>= 0.20.3, < 2.0)
```
Updating Bitters will fix that.
=> Upgrade to Bitters 2.0.4

lib/suspenders/generators/base.rb, lib/suspenders/generators/stylesheet_base_generator.rb, templates/descriptions/advisories.md, templates/descriptions/analytics.md, templates/descriptions/ci.md, templates/descriptions/compression.md, templates/descriptions/db_optimizations.md, templates/descriptions/deployment.md, templates/descriptions/email.md, templates/descriptions/factories.md, templates/descriptions/force_tls.md, templates/descriptions/forms.md, templates/descriptions/inline_svg.md, templates/descriptions/jobs.md, templates/descriptions/js_driver.md, templates/descriptions/json.md, templates/descriptions/lint.md, templates/descriptions/manifest.md, templates/descriptions/preloader.md, templates/descriptions/profiler.md, templates/descriptions/pull_requests.md, templates/descriptions/runner.md, templates/descriptions/single_redirect.md, templates/descriptions/static.md, templates/descriptions/stylelint.md, templates/descriptions/stylesheet_base.md, templates/descriptions/testing.md, templates/descriptions/timeout.md, templates/descriptions/views.md
This adds a description to all of our generators, except for the main
one. The main one will continue to use the `USAGE` file.
The descriptions are stored in a Markdown file under
`templates/descriptions`, named after the generator. For example,
`Suspenders::ViewsGenerator` is described by
`templates/descriptions/views.md`.
A little metaprogramming is used in the parent class to make this
seamless for the generators.
---
While here, fix a few generators:
- ~~`.env` is now `.sample.env`.~~ #1036 
- Move the `remove_prior_config` method up, so we don't remove the
config that we just added.
=> Describe generators

templates/partials/db_optimizations_configuration.rb, templates/partials/email_smtp.rb
Prior to this PR, using the `DbOptimizationsGenerator` would result in an invalid `config/environments/development.rb` containing the following code:
```ruby
config.action_mailer.raise_delivery_errors = falseconfig.after_initialize do
Bullet.enable = true
Bullet.bullet_logger = true
Bullet.rails_logger = true
end
```
Commit b15c906 moved the injected code to a template, and we apparently lost some necessary whitespace in the process.
While we're here, this PR also adds some additional indentation to some of the injected partials so that the generated files look a bit nicer.
=> Fix missing whitespace

lib/suspenders/generators/js_driver_generator.rb, templates/spec_helper.rb
This commit replaces the deprecated chromedriver-helpers gem with the still supported webdrivers gem.
It's a backport of a change made to a suspenders-generated project, which has been happily running with this configuration for about a month now.
Fixes #1030
=> Switch from chromedriver-helpers to webdrivers.

lib/suspenders/generators/advisories_generator.rb, lib/suspenders/generators/ci_generator.rb, lib/suspenders/generators/db_optimizations_generator.rb, lib/suspenders/generators/factories_generator.rb, lib/suspenders/generators/forms_generator.rb, lib/suspenders/generators/inline_svg_generator.rb, lib/suspenders/generators/jobs_generator.rb, lib/suspenders/generators/js_driver_generator.rb, lib/suspenders/generators/json_generator.rb, lib/suspenders/generators/preloader_generator.rb, lib/suspenders/generators/production/timeout_generator.rb, lib/suspenders/generators/profiler_generator.rb, lib/suspenders/generators/static_generator.rb, lib/suspenders/generators/stylesheet_base_generator.rb, lib/suspenders/generators/testing_generator.rb, spec/features/api_spec.rb, spec/features/new_project_spec.rb, spec/support/suspenders.rb
`Bundler.with_clean_env` has been deprecated in favor of
`Bundler.with_unbundled_env`
=> Replace deprecated Bundler method

lib/suspenders/generators/lint_generator.rb, spec/features/lint_spec.rb, templates/hound.yml
This commit adds the [standard] gem, and requires the standard rake task
in the Rakefile.
It also disables RuboCop on Hound, since standard is meant to replace
RuboCop.
[standard]: https://github.com/testdouble/standard
Co-authored-by: Daniel Colson <danieljamescolson@gmail.com>
=> Add standard to lint generator

lib/suspenders/generators/app_generator.rb, lib/suspenders/generators/production/timeout_generator.rb, lib/suspenders/generators/profiler_generator.rb, spec/features/new_project_spec.rb, spec/features/profiler_spec.rb
In a056e1a85398e7140ce60b7c14721f9149cfa2b6 we migrated from `.env` to
`.sample.env`. Some stray `.env` files were left behind; fix those.
=> Finish .sample.env migration

.github/workflows/main.yml
CI currently runs on manual work flow dispatches for the `main` branch.
This updates CI to run on pushes to the `main` branch.
=> Run CI on pushes to main

templates/postgresql_database.yml.erb
As part of building the Suspenders app, we run `bin/rails db:create`.
This runs under `RAILS_ENV=development` but [creates both the development
and test databases][].
[creates both the development and test databases]: https://github.com/rails/rails/blob/de630cdac82a67edd342a9693d96bcda91a54c08/activerecord/lib/active_record/tasks/database_tasks.rb#L549
There was recent work to [combine the `DATABASE_URL` environment variable
with the existing `config/database.yml`] in ActiveRecord, with the YAML
providing the base and the env var overriding and filling in missing
pieces. This allows us to set the `DATABASE_URL` for CI and have the
tests pick it up.
[combine the `DATABASE_URL` environment variable with the existing `config/database.yml`]: …
=> Pull in the DATABASE_URL explicitly

lib/suspenders/generators/app_generator.rb
In this PR, we are removing the `spring stop` command from `AppGenerator`.
I thought it would be useful to run `spring stop` for individual generators, but within the context where `spring stop` is being removed we generate a full application with the `suspenders` command, so there's no risk of spring running or interfering with anything.
=> Remove remaining spring references

spec/support/match_contents_matcher.rb
The `match_contents` RSpec matcher is used to match on the contents of files manipulated by a generator.  When a failure happens, however, the reason why it happens is often not clear.
This PR improves the error message and includes the contents of the target file in it to allow for better debugging.
=> Introduce a clear failure message for the match_contents RSpec matcher

spec/support/fake_bundler_matchers.rb
The error message when bundler is given unexpected arguments is switching actual with expected arguments. This PR fixes that problem.
=> Fix bundler RSpec matcher error messages

lib/suspenders/app_builder.rb, spec/features/new_project_spec.rb
This change was [originally made in a suspenders-based app to fix a problem
we were having with images not rendering in emails][1]. This commit replicates
the fix up-stream for future suspenders users.
The change fixes image URLs in emails by adding a protocol to the
ActionMailer asset_host setting.
While the setting is called "host", based on the examples in the Rails
documentation, it could be more accurately described as a "URL-prefix" --
all of the examples include a protocol as well as a host.
Prior to this change, image URLs were generated in emails from production
environments with a protocol-relative URL (e.g. //example.com/image.png),
and were not rendering correctly in the various mail clients we tested.
[1]: https://github.com/thoughtbot/albaik-web/pull/609
=> Fix ActionMailer asset host in production.

lib/suspenders.rb, lib/suspenders/exit_on_failure.rb, lib/suspenders/generators/app_generator.rb, lib/suspenders/generators/base.rb, spec/features/api_spec.rb, spec/support/feature_test_helpers.rb, spec/suspenders/app_generator_spec.rb, spec/suspenders/exit_on_failure_spec.rb, spec/suspenders/generators/base_spec.rb
Closes [#1080](https://github.com/thoughtbot/suspenders/issues/1080)
This task is part of our "Rescue" board: https://github.com/thoughtbot/suspenders/projects/1
`bin/suspenders` is now halting on error. Not halting on error was a huge source of confusion for Suspenders users. Some examples of issues we are resolving here:
- If using the wrong Ruby version, Suspenders will fail loudly. Currently, Suspenders is limited to a single Ruby version (we'll make the Ruby version flexible in another PR.) Example:
```
create  storage/.keep
create  tmp/storage
create  tmp/storage/.keep
remove  config/initializers/cors.rb
remove  config/initializers/new_framework_defaults_6_1.rb
force  Gemfile
run  bundle install
Your Ruby version is 2.7.5, but your Gemfile specified 2.7.4
```
No more output. The …
=> Make Suspenders abort when something goes wrong

suspenders.gemspec
Closes https://github.com/thoughtbot/suspenders/issues/1081
References:
- https://github.com/thoughtbot/suspenders/issues/1081
- https://github.com/thoughtbot/suspenders/issues/1047
Suspenders relies on the `Bundler.with_unbundled_env` method, which is only available on Bundler >= 2.1.0
When Suspenders was tied to Ruby 2.6.6 (when https://github.com/thoughtbot/suspenders/issues/1047 was reported), which had Bundler 1.7.2 as a default gem, it could happen that Rails would pick up Bundler 1.7.2 and Suspenders would thus fail when generating a new application.
Now Suspenders uses Ruby 2.7.4, which has Bundler 2.1.4 as a default gem - so even if we manually install Bundler 1.7.2, Rails won't pick that version up in `Gemfile.lock`, so we probably don't risk running into the Bundler problem …
=> Enforce bundler >= 2.1.0

suspenders.gemspec
Closes https://github.com/thoughtbot/suspenders/issues/1055
Changes `suspenders.gemspec` to not depend on git. Additionally, we can safely remove `s.test_files` since [its use is no longer recommended](https://github.com/rubygems/guides/issues/90) and was introduced in the Suspenders codebase many years ago.
=> Drop use of git in gemspec

lib/suspenders/app_builder.rb, lib/suspenders/generators/app_generator.rb
This commit ensures that `bundle exec rails db:migrate` is run before the app is generated. Prior to this commit, running `./bin/setup` in the app generated by suspenders would have resulted in a failure due to a pending migration.
Issues
------
Closes #1095
Co-authored-by: Thiago Silva <thiagoaraujos@gmail.com>
=> Run database migrations as the last step of bin/suspenders 

bin/suspenders
Sometimes `bin/suspenders` would pick up the maximum installed Rails
version but Suspenders would freeze the Rails version to
`Suspenders::RAILS_VERSION` on the generated application -- and
therefore `bin/suspenders` would fail with a confusing error.
A fix for that was attempted in this commit:
https://github.com/thoughtbot/suspenders/commit/f3ce221d553e611d1c8e32a22cafd9fa214999f8
However, that fix tried to use Bundler, which is only available in the
context of an application that has a Gemfile. It was only tested on
the local development environment, which runs within a Bundler
context. We'll do what we can to not repeat that error in the future.
The correct fix should find a compatible Rails gem using rubygem's
API (and not Bundler) and then activate it so that `bin/suspenders` can …
=> Fix bundler error on bin/suspenders script

lib/suspenders/app_builder.rb, lib/suspenders/generators/app_generator.rb, spec/support/feature_test_helpers.rb
Problem
-------
Some facts
- Suspenders includes itself in the generated application's `Gemfile`
- Suspenders generators run in the context of the generated
applications
- Generated applications include Suspenders as a development dependency
Given the last item, if we're running Suspenders in development, we'd
end up with two copies of it: the development copy and a gem copy. The
problem is that:
- The development copy will start up Suspenders
- Generators, since they run in the context of an application, will be
picked up from the gem
Therefore, running `bin/suspenders` in development may put us in a
situation where the development copy has changes that the gem copy
does not, which means our code changes would not fully apply.
To prevent such a mismatch, the existing solution is to run …
=> Automate generator lookup in the development environment

README.md, lib/suspenders/generators/jobs_generator.rb, lib/suspenders/generators/production/manifest_generator.rb, spec/features/new_project_spec.rb, templates/Procfile, templates/descriptions/jobs.md, templates/descriptions/runner.md, templates/sample_env
Closes #1074 
All jobs are enqueued to "default" queue. In Rails 6.1 we won't need the application.rb tweak for action_mailer, action_mailbox and active_storage (https://github.com/mperham/sidekiq/wiki/Active-Job#queues).
Using Sidekiq through ActiveJob is significantly slower than using pure Sidekiq workers (https://github.com/mperham/sidekiq/wiki/Active-Job#performance), maybe a migration would be nice in the future
=> Replace Delayed::Job with Sidekiq

lib/suspenders/actions.rb, lib/suspenders/app_builder.rb, lib/suspenders/generators/advisories_generator.rb, lib/suspenders/generators/jobs_generator.rb, lib/suspenders/version.rb, spec/features/new_project_spec.rb, templates/active_job.rb
This commit does the bare minimum to support Rails 6.1.6.1
Because the `gem` command is no longer reversible, we decided to override the method by borrowing as much from the [existing method](https://github.com/rails/rails/blob/04972d9b9ef60796dc8f0917817b5392d61fcf09/railties/lib/rails/generators/actions.rb#L22). The main difference being that we call `append_file` instead of `gsub_file`, so that we can preserve reversibility. However, https://github.com/thoughtbot/suspenders/pull/1066 provides a more elegant solution.
Closes https://github.com/thoughtbot/suspenders/issues/1060
=> Support Rails 6.1.6.1

README.md, lib/suspenders.rb, lib/suspenders/generators/accessibility_generator.rb, spec/suspenders/generators/accessibility_generator_spec.rb
Create the `Suspenders::AccessibilityGenerator` to install
[capybara_accessibility_audit][] and [capybara_accessible_selectors][].
[capybara_accessibility_audit]: https://github.com/thoughtbot/capybara_accessibility_audit
[capybara_accessible_selectors]: https://github.com/citizensadvice/capybara_accessible_selectors
=> Introduce Accessibility tooling Generator

CONTRIBUTING.md
The link to the style guide shared in the CONTRIBUTING doc was broken. thoughtbot's guides changed location some time ago, and the Ruby style guide lives on this new URL.
=> Fix style guides broken link

spec/support/fixtures/dummy_app/config/environments/development.rb
When running the specs, the following linter message is displayed at the end:
```
standard: Run `rake standard:fix` to automatically fix some problems.
spec/support/fixtures/dummy_app/config/environments/development.rb:10:42: Layout/SpaceInsideHashLiteralBraces: Space inside empty hash literal braces detected.
```
This small PR fixes that problem. It's a small contribution to get started with contributing to the project :)
=> Fix Layout/SpaceInsideHashLiteralBraces linter problem

CODEOWNERS
As part of our work to easily identify the maintainers of our open source projects, this PR adds a [CODEOWNER](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) file.
What it does:
- Automatically include people as reviewers on pull requests
- Provide a clear reference of who should be answering questions and making decisions
- Make it easy to search for projects which need a new owner when somebody leaves
=> Create CODEOWNERS [ci-skip]

lib/suspenders/generators/js_driver_generator.rb, templates/capybara_silence_puma.rb
Capybara was configured to silence Puma in #981 to prevent Puma 
startup messages being output when running specs with `js: true`.
This configuration has since been updated in [rspec-rails](https://github.com/rspec/rspec-rails/pull/2289), so we can 
remove it here.
=> Remove redundant Capybara config

.standard.yml
Since the current configuration for Standard defaults to the executing Ruby version, newer contributions are failing because the codebase doesn't use the [anonymous rest][] syntax made available in Ruby 3.2.
The gem current supports a [Ruby Version Range][] with 3.0.5 as the minimum, so we should pass that to Standard in its [YAML Options][].
[anonymous rest]: https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/
[Ruby Version Range]: https://github.com/thoughtbot/suspenders/blob/761c4134308f77f52dd25a228c7cedfd14dafe82/lib/suspenders/version.rb#L4-L7
[YAML Options]: https://github.com/standardrb/standard#yaml-options
=> Configure Standard to use Ruby 3.0

README.md, templates/Gemfile.erb
With the release of `rails` 4.1, `Timecop.freeze` can be replaced with `travel_to`
``` ruby
Timecop.freeze 1.week.ago do
end
travel_to 1.week.ago do
end
```
Read more in the [TimeHelpers](https://github.com/rails/rails/blob/a6f55fe257512731d7f3f41976648d99e9ec95be/activesupport/lib/active_support/testing/time_helpers.rb#L43) module
inspired by  http://brandonhilkert.com/blog/rails-4-1-travel-to-test-helper
=> Removed `timecop` gem in favor of `travel_to`

NEWS.md, README.md, lib/generators/suspenders/accessibility_generator.rb, lib/suspenders.rb, lib/suspenders/generators.rb, test/generators/suspenders/accessibility_generator_test.rb, test/suspenders/generators_test.rb, test/test_helper.rb
Introduce `suspenders:accessibility` generator
Ported over from #1105
Installs [capybara_accessibility_audit] and
[capybara_accessible_selectors].
`./bin/rails g suspenders:accessibility`
Introduces `Suspenders::Generators::APIAppUnsupported` module for
generators that cannot be run in an [API only][] application.
This uses a [concern][] to ensure we raise an error before the generator
including the module invokes any of its methods.
If you want to manually run this generator, simply do the following:
1. `cd test/dummy`
1. `touch Gemfile`
1. `./bin/rails g suspenders:accessibility`
Confirm the `Gemfile` and `Gemfile.lock` contains the gems.
To test that it won't work on an API only application, comment out or remove
`config.api_only = true` from `test/dummy/config/application.rb` and run …
=> Introduce `suspenders:accessibility` generator

bin/rails
This is a work around for an [issue][] with `vim-test`. Borrowed an [existing][]
`./bin/rails` configuration from an [Engine][], which is very similar to a
[plugin][]. The only difference is that we do not need the `ENGINE_ROOT`
setting.
[issue]: https://github.com/vim-test/vim-test/issues/477
[existing]: https://github.com/rails/rails/blob/main/railties/lib/rails/generators/rails/plugin/templates/bin/rails.tt
[Engine]: https://guides.rubyonrails.org/engines.html
[plugin]: https://guides.rubyonrails.org/plugins.html
=> Introduce `./bin/rails` to fix broken test runner

NEWS.md, README.md, lib/generators/suspenders/inline_svg_generator.rb, lib/generators/templates/inline_svg/inline_svg.rb, test/generators/suspenders/inline_svg_generator_test.rb
Ports the existing generator to Suspenders 3.0.
To do:
Add suspenders to the `Gemfile`.
```ruby
group :development, :test do
gem "suspenders", git: "https://github.com/thoughtbot/suspenders", branch: "suspenders-3-0-0-inline-svg-generator"
end
```
Install and run the generator:
```
bundle
bin/rails g suspenders:inline_svg
```
=> Introduce `suspenders:inline_svg` generator

NEWS.md, README.md, lib/generators/suspenders/factories_generator.rb, lib/generators/templates/factories/factories.rb, lib/generators/templates/factories/factories_spec.rb, lib/generators/templates/factories/factories_test.rb, lib/generators/templates/factories/factory_bot_rspec.rb, lib/suspenders/generators.rb, test/generators/suspenders/factories_generator_test.rb
Maintains functionally with the [existing generator][] while adding
support for the [default Rails test suite]. With this change, the
generator can be invoked on a Rails application that use RSpec and the
default Rails test suite.
Adds generator which adds a test to lint all Factories in an effort to
improve developer experience.
Additionally, we remove the generation of the `dev:prime` task as we
felt that should be the responsibly of another generator.
Review is easier when compared with the [existing generator][].
Additionally, if you want to manually test these changes, spin up a new rails app and add the following:
```ruby
group :development, :test do
gem "suspenders", git: "https://github.com/thoughtbot/suspenders", branch: "factory-bot-generator"
end
```
[existing generator]: …
=> Introduce `suspenders:factories` generator

NEWS.md, README.md, lib/generators/suspenders/advisories_generator.rb, test/generators/suspenders/advisories_generator_test.rb, test/test_helper.rb
Uses the [bundler-audit][] gem to update the local security database and
show any relevant issues with the app's dependencies. This generator is
only responsible for installing the gem.
The [original implementation][] was written in 2014, and is no longer
relevant. This is because the gem ships [with a Rake task][] that can be
set as the default task, which will be addressed in #1144
Also exposes `backup_file` and `restore_file` test helpers into the
public API.
[bundler-audit]: https://github.com/rubysec/bundler-audit
[original implementation]: https://github.com/thoughtbot/suspenders/commit/e23157ede1477a6e3e1163516281cfda10b479c6
[with a Rake task]: https://github.com/rubysec/bundler-audit#rake-tasks
=> Introduce `suspenders:advisories` generator

NEWS.md, README.md, lib/generators/suspenders/styles_generator.rb, test/generators/suspenders/accessibility_generator_test.rb, test/generators/suspenders/inline_svg_generator_test.rb, test/generators/suspenders/styles_generator_test.rb, test/test_helper.rb
Configures applications to use [PostCSS][1] or [Tailwind][2] via
[cssbundling-rails][3]. Defaults to PostCSS with [modern-normalize][8], with
the option to override via `--css=tailwind`. These options were pulled from the
[supported list of options][4] in Rails.
Also creates additional stylesheets if using PostCSS.
We choose to use [cssbundling-rails][4] instead of [dartsass-rails][5] or
[tailwindcss-rails][6] (or even just css) because we want to rely on Node to
process the CSS. Although we could have chosen to avoid using Node altogether,
we feel it's better to support it since we'll need it for additional generators,
like [StyleLintGenerator][7], and to support [modern-normalize][8].
Updates `within_api_only_app` by allowing support to conditionally comment out
the api configuration. …
=> Introduce `suspenders:styles` generator

README.md, lib/generators/suspenders/styles_generator.rb, test/generators/suspenders/styles_generator_test.rb
These modifications were not captured before merging #1145, presumably because
of an issue with GitHub CLI.
=> Modify `suspenders:styles`

NEWS.md, README.md, lib/generators/suspenders/jobs_generator.rb, lib/generators/templates/active_job/active_job.rb, test/generators/suspenders/jobs_generator_test.rb, test/test_helper.rb
Ports the existing generator to Suspenders 3.0.
=> Introduce `suspenders:jobs` generator

NEWS.md, README.md, lib/generators/suspenders/lint_generator.rb, lib/generators/templates/lint/better_html_spec.rb, lib/generators/templates/lint/better_html_test.rb, lib/generators/templates/lint/config_better_html.yml, lib/generators/templates/lint/config_initializers_better_html.rb, lib/generators/templates/lint/erb-lint.yml, lib/generators/templates/lint/erblint.rake, lib/generators/templates/lint/eslintrc.json, lib/generators/templates/lint/prettierrc, lib/generators/templates/lint/rubocop.yml.tt, lib/generators/templates/lint/stylelintrc.json, test/generators/suspenders/lint_generator_test.rb, test/test_helper.rb
Closes #1107
Closes #1143
Creates a holistic linting solution that covers JavaScript, CSS, Ruby
and ERB.
Introduces `eslint` and `stylelint` NPM commands that leverage
[@thoughtbot/eslint-config][] and [@thoughtbot/stylelint-config][].
```
yarn run eslint
yarn run stylelint
```
Also introduces `.prettierrc` based off of our [Guides][].
[@thoughtbot/eslint-config]: https://github.com/thoughtbot/eslint-config
[@thoughtbot/stylelint-config]: https://github.com/thoughtbot/stylelint-config
[Guides]: https://github.com/thoughtbot/guides/blob/main/javascript/README.md#formatting
Introduces `rake standard` which also runs `erblint` to lint ERB files
via [better_html][], [erb_lint][] and [erblint-github][].
[better_html]: https://github.com/Shopify/better-html
[erb_lint]: …
=> Introduce `suspenders:lint` generator

NEWS.md, README.md, bin/rails, lib/generators/suspenders/rake_generator.rb, lib/suspenders.rb, lib/suspenders/engine.rb, lib/tasks/suspenders.rake, test/generators/suspenders/rake_generator_test.rb
Add necessary files to make the [plugin][] an [engine][], which
automatically loads Rake tasks located in `lib/tasks`. This means when
the `suspenders` gem is installed, the consumer can run `bundle exec
rake suspenders:rake`, and any future tasks.
Because `suspenders:lint` and `suspenders:advisories` may not
necessarily have been invoked, we need to check if those gems are
installed.
[plugin]: https://guides.rubyonrails.org/plugins.html
[engine]: https://guides.rubyonrails.org/engines.html
1. Spin up a new Rails application.
```sh
rails new rake_demo
```
1. Scaffold a domain in order to generate passing tests.
```sh
bin/rails g scaffold post title
bin/rails db:migrate
```
1. Install suspenders on this branch.
```ruby
group :development, :test do
gem "suspenders", github: …
```
=> Introduce `suspenders:rake` generator

lib/generators/suspenders/lint_generator.rb, lib/generators/templates/lint/tailwind.stylelintrc.json, lib/suspenders/generators.rb, test/generators/suspenders/lint_generator_test.rb, test/test_helper.rb
When we introduced #1148 we did not test it against applications that invoked
`suspenders:styles --css=tailwind`.
=> Fix stylelint violations when using Tailwind

NEWS.md, README.md, lib/generators/suspenders/views_generator.rb, lib/generators/templates/views/flashes.html.erb, test/generators/suspenders/views_generator_test.rb
Configures flash messages, page titles via the [title][] gem, and sets the
document [lang][].
[title]: https://github.com/calebhearth/title
[lang]: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang
It should be noted that running `rails gscaffold` generates [views][] that
contain the flash. Although we could have [overridden][] this generator, that
would risk drift between our overridden generator and the one in Rails core.
Additionally, we decided to remove the `FlashesHelper` introduced in
[6c562b95e2e3c7ea31a04e6ef71c6a44b0b9ab2f][] since that is not a pattern we
currently use.
[views]: https://github.com/rails/rails/blob/main/railties/lib/rails/generators/erb/scaffold/templates/index.html.erb.tt
[overridden]: …
=> Introduce `suspenders:views` generator

NEWS.md, README.md, lib/generators/suspenders/setup_generator.rb, lib/generators/templates/setup/bin_setup.rb, lib/generators/templates/setup/brewfile, lib/generators/templates/setup/dev_prime.rb, test/generators/suspenders/setup_generator_test.rb
Replaces the [default setup script][] provided by Rails. The trade-off being
that the implementation is simple, but the cost is we risk drifting from Rails.
After attempting to use [gsub_file][] and [insert_into_file][], it felt simpler
to just override the file completely.
Clobber and precompile assets during setup if using [Sprockets][]. This
is helpful in cases where one might switch branches frequently, which
can result in broken assets.
Additionally, we [setup the test environment][] to avoid issues with asset
compilation in tests.
[default setup script]: https://github.com/rails/rails/blob/main/railties/lib/rails/generators/rails/app/templates/bin/setup.tt
[gsub_file]: https://rubydoc.info/gems/thor/Thor/Actions#gsub_file-instance_method
[insert_into_file]: …
=> Introduce `suspenders:setup` generator

NEWS.md, README.md, lib/generators/suspenders/tasks_generator.rb, lib/generators/templates/tasks/dev.rake, test/generators/suspenders/tasks_generator_test.rb
Relates to #1157
For now, this generator simply creates `dev.rake` which contains [dev:prime][].
Note that we'll want this generator to run **after** `suspenders:factories`.
If future application specific tasks need to be added, we can use this
generator. However, this should not be confused with the existing pattern of
creating tasks under the suspenders namespace, such as the existing
`lib/tasks/suspenders.rake`. Tasks under this namespace cannot be edited by the
consumer, whereas tasks generated by `suspenders:tasks` are intended to be
edited by the consumer.
[dev:prime]: https://thoughtbot.com/blog/priming-the-pump
=> Introduce `suspenders:tasks` generator

NEWS.md, README.md, lib/generators/suspenders/email_generator.rb, lib/generators/templates/email/email_interceptor.rb, test/generators/suspenders/email_generator_test.rb
Creates [email interceptor][] to ensure emails are sent to preconfigured
addresses in non-production environments. Drops support for [Recipient
Interceptor][], since this functionality is supported in Rails Core.
In order to enable the interceptor, set `EMAIL_RECIPIENTS` to a
comma-separated list.
```sh
INTERCEPTOR_ADDRESSES="user_1@example.com,user_2@example.com" bin/rails s
```
Configures [default_url_options][] in `test` and `development`
environments so that `*_url` helpers will work.
Note that we do not configure `production`, since we've determined the
`delivery_method` is something each project will configure
independently. This means we'll just use the [default configuration][],
which is `smtp`.
[email interceptor]: https://guides.rubyonrails.org/action_mailer_basics.html#intercept …
=> Introduce `suspenders:email` generator

lib/generators/suspenders/lint_generator.rb, test/generators/suspenders/lint_generator_test.rb
After the `v4.0.0` release of [@thoughtbot/stylelint-config][], the
errors mentioned in [this issue][] no longer appear.
This alleviates us from having to pin these dependencies.
[@thoughtbot/stylelint-config]:
https://github.com/thoughtbot/stylelint-config/releases/tag/v4.0.0
[this issue]: https://github.com/thoughtbot/stylelint-config/issues/46
=> Update front-end linting dependencies

README.md, lib/generators/suspenders/views_generator.rb, test/generators/suspenders/views_generator_test.rb
Turbo 8 introduced [InstantClick][]. An unintended side-effect of this
feature is that page requests are [not debounced][] when a user hovers
over a link. This is a concern for two reasons:
1. It creates an unnecessary burden on the server, which could affect
rate limiting.
2. It can artificially inflate our metrics.
[InstantClick]: https://turbo.hotwired.dev/handbook/drive#prefetching-links-on-hover
[not debounced]:https://github.com/hotwired/turbo/pull/1181#issuecomment-1936505362
=> Disable Turbo's InstantClick

lib/generators/templates/setup/bin_setup.rb
Follow-up to #1157
After merging #1156, this command no longer works, since it's assumed the app was generated with the `--skip-test` flag.
=> Setup Generator: Remove call to `test:prepare`

lib/generators/suspenders/lint_generator.rb, lib/generators/templates/lint/prettierignore, test/generators/suspenders/lint_generator_test.rb
The upcoming `suspenders:ci` generator caches Ruby dependencies in `vendor/bundle`.
This commit ensures we ignore that path.
=> Lint Generator: Introduce `.prettierignore`

NEWS.md, README.md, lib/generators/suspenders/prerequisites_generator.rb, lib/generators/templates/prerequisites/node-version.tt, lib/suspenders/version.rb, test/generators/suspenders/prerequisites_generator_test.rb, test/suspenders_test.rb
Follow-up to #1148 and #1145
In #1148 and #1145, we introduce the need for yarn to manage dependencies. Those commits failed to establish a `.node-version` file, which [normally would be generated][1] by Rails if **not** using `import-maps`.
This commit introduces that file, which compliments the existing `.ruby-version` file that is generated.
I chose to use `.node-version` and not `.nvm` or `.tool-versions` to keep parity with Rails.
The [current version][2] set by Rails is `18.15.0`, but a [future commit][3] aims to use the latest LTS value. This commit aims to use that version.
This commit will also benefit a future `suspenders:ci` generator, since the `.node-version` file will be used in CI.
[1]: https://github.com/rails/rails/blob/68b20b6513fe56ca80e4966628c231b4d6113bea/railties/lib …
=> Introduce `suspenders:prerequisites` generator

NEWS.md, README.md, lib/generators/suspenders/ci_generator.rb, lib/generators/templates/ci/ci.yml.tt, lib/generators/templates/ci/dependabot.yml, lib/suspenders/generators.rb, test/generators/suspenders/ci_generator_test.rb, test/suspenders/generators_test.rb, test/test_helper.rb
Creates CI template to be run via [GitHub Actions][ga] based on a
[similar template][ci template] that will be generated in an upcoming
Release of Rails.
Also create a [Dependabot][dependabot] file based off the [the upcoming
release][ci template].
Raises if the application is not using PostgreSQL, since our CI template
assumes that adapter.
Because this generator can be run in an existing application, we add
conditional checks for some jobs. However, this generator is intended
to be run as part of our holistic `suspenders:install:web` which will be
introduced in #1152.
Once Rails is released to contain a CI template, we will need to
consider how we want to handle conflicts between its file and ours, but
for now, we do not need to worry about that.
[ga]: https://docs.github.com/en/actions …
=> Introduce `suspenders:ci` generator

lib/generators/templates/ci/ci.yml.tt, lib/generators/templates/ci/dependabot.yml
Follow-up to #1172
Fixes indentation ensuring a valid syntax. Also fixes linting violations raised by `yarn lint`.
=> CI Generator: Fix indentation and linting violations.

lib/suspenders/generators.rb
For some reason #1175 passed, but CI for #1174 is failing.
=> Fix additional linting violations

lib/generators/suspenders/lint_generator.rb, test/generators/suspenders/lint_generator_test.rb
Supports #1152
We found that we needed to run this generator last in `suspenders:install:web` to ensure any potential violation was resolved.
Instead, we'll just make that the responsibility of `suspenders:install:web`.
=> Lint Generator: No longer fix violations after invocation

lib/generators/suspenders/lint_generator.rb, lib/generators/templates/lint/package.json, test/generators/suspenders/lint_generator_test.rb
In order to avoid raising `No such file or directory`, we create a `package.json` file if one does not exist. We borrow a template from [cssbundling-rails][].
[cssbundling-rails]: https://github.com/rails/cssbundling-rails/blob/09d81cb0accf00abb77d8af5b24f5aad0b71a57a/lib/install/package.json#L3
=> Lint Generator: Handling missing `package.json`

NEWS.md, README.md, lib/suspenders.rb, lib/suspenders/cleanup/organize_gemfile.rb, lib/tasks/suspenders.rake, lib/tasks/suspenders_tasks.rake, test/fixtures/files/gemfile_clean, test/fixtures/files/gemfile_messy, test/suspenders/cleanup/organize_gemfile_test.rb
Introduce `Suspenders::Cleanup::OrganizeGemfile` class and corresponding task in an effort to reduce duplicate groups in the modified Gemfile.
This is because the [gem_group][] method does not modify existing groups. I've opened [#49512][] in an effort to fix this, but until then, this task will suffice.
This class is designed to be run after `suspenders:install:web`, and does not account for all edge cases. For example, it assumes gems are grouped by symbols (i.e. :test and not "test"), and does not account for inline syntax:
```ruby
gem 'my-gem', group: [:cucumber, :test]
```
We could consider extracting this into a Gem (with a fun name, of course. Maybe "Polish"), but for now, I think this simple procedural code if just fine.
Additionally, this commit removes duplicate Rake task that …
=> Introduce `suspenders:cleanup:organize_gemfile` task

NEWS.md, README.md, lib/generators/suspenders/production/environment_generator.rb, test/fixtures/files/environments/production.rb, test/generators/suspenders/production/environment_generator_test.rb
Creates generator to configuration the production environment. For now,
this means [requiring a master key][master key].
Drops configuration for [asset_host][], since that should be an
infrastructure decision.
In an effort to distinguish between the development environment
configuration in #1149, we use the `production` namespace.
[master key]: https://guides.rubyonrails.org/configuring.html#config-require-master-key
[asset_host]: https://guides.rubyonrails.org/configuring.html#config-asset-host
=> Introduce `suspenders:production:environment` generator

NEWS.md, README.md, lib/generators/suspenders/test/environment_generator.rb, test/fixtures/files/environments/test.rb, test/generators/suspenders/test/environment_generator_test.rb
Configures test environment. This differs from #1156 in that this commit is concerned with configuration, where that commit was concerned with generating a holistic test suite. It's also possible to run each generator independently, and the two should not rely on one another.
Disables [action_dispatch.show_exceptions][] in an effort to [improve failure output][comment].
Enables [raise_on_missing_translations][] to keep parity with the same setting in development #1149
[action_dispatch.show_exceptions]: https://edgeguides.rubyonrails.org/configuring.html#config-action-dispatch-show-exceptions
[comment]: https://github.com/thoughtbot/suspenders/pull/1149#discussion_r1424458925
[raise_on_missing_translations]: https://guides.rubyonrails.org/configuring.html#config-i18n-raise-on-missing-transl …
=> Introduce `suspenders:test:environment` generator

NEWS.md, README.md, lib/generators/suspenders/development/environment_generator.rb, test/fixtures/files/environments/development.rb, test/generators/suspenders/development/environment_generator_test.rb
Creates generator to configure the development environment. Keeps parity
with Rails as much as possible in an effort to avoid drift with Rails
standards.
It's possible a future release of Rails will alleviate us from having to
do the following:
- enable `active_model.i18n_customize_full_message` which is being
addressed in [#50406][]
- enable `active_record.query_log_tags_enabled` which is being addressed
in [#51342][]
[#50406]: https://github.com/rails/rails/pull/50406
[#51342]: https://github.com/rails/rails/pull/51342
=> Add `suspenders:development:environment` generator

NEWS.md, README.md, lib/generators/suspenders/environments/development_generator.rb, lib/generators/suspenders/environments/production_generator.rb, lib/generators/suspenders/environments/test_generator.rb, test/generators/suspenders/environments/development_generator_test.rb, test/generators/suspenders/environments/production_generator_test.rb, test/generators/suspenders/environments/test_generator_test.rb
Follow-up to #1151, #1182, and #1149
Using the `Environments` namespace feels more appropriate, since this keeps parity with Rails' directory structure.
=> Clean Up: Use `Environments` namespace

lib/generators/suspenders/accessibility_generator.rb, test/generators/suspenders/accessibility_generator_test.rb
In order to avoid the following failure in CI, we need to load the latest build (not release) of capybara_accessibility_audit.
```
NoMethodError: undefined method `configure' for module RSpec (NoMethodError)
RSpec.configure do |config|
```
For reference, [this commit][] fixes the issue.
[this commit]: https://github.com/thoughtbot/capybara_accessibility_audit/commit/0ee6922ef19a391fb617778ef730af30b2680759
=> AccessibilityGenerator: Update gem declaration

lib/generators/suspenders/advisories_generator.rb, lib/generators/suspenders/rake_generator.rb, test/fixtures/files/Rakefile, test/fixtures/files/Rakefile_advisories, test/generators/suspenders/advisories_generator_test.rb, test/generators/suspenders/rake_generator_test.rb
Prior to this commit, the Rakefile required `bundler-audit` and `standard` in all environments. This prevented Rake from running in production, because those dependencies are only loaded in `:development` and `:test`.
=> Rakefile: Conditionally require local dependencies

lib/generators/suspenders/accessibility_generator.rb, lib/generators/suspenders/advisories_generator.rb, lib/generators/suspenders/ci_generator.rb, lib/generators/suspenders/email_generator.rb, lib/generators/suspenders/factories_generator.rb, lib/generators/suspenders/inline_svg_generator.rb, lib/generators/suspenders/jobs_generator.rb, lib/generators/suspenders/lint_generator.rb, lib/generators/suspenders/prerequisites_generator.rb, lib/generators/suspenders/rake_generator.rb, lib/generators/suspenders/setup_generator.rb, lib/generators/suspenders/styles_generator.rb, lib/generators/suspenders/tasks_generator.rb, lib/generators/suspenders/testing_generator.rb, lib/generators/suspenders/views_generator.rb, lib/suspenders.rb, lib/suspenders/cleanup/generate_readme.rb, lib/tasks/suspenders.rake, test/generators/suspenders/accessibility_generator_test.rb, test/generators/suspenders/inline_svg_generator_test.rb, test/generators/suspenders/jobs_generator_test.rb, test/generators/suspenders/lint_generator_test.rb, test/suspenders/cleanup/generate_readme_test.rb
Create README based off the `desc` of the generators.
We chose to create a custom class instead of a traditional generator because this script is intended to be run in the [application template][] as a Rake task. It is not intended to be run as a standalone generator, since it only makes sense to be run on concert with `suspenders:install:web`.
Updates all generator descriptions to use Herdoc syntax to ensure consistent line breaks.
A follow-up commit will update the descriptions to work better in a README.
[application template]: https://guides.rubyonrails.org/rails_application_templates.html
=> Dynamically generate README

test/fixtures/files/rails_helper.rb, test/generators/suspenders/factories_generator_test.rb, test/generators/suspenders/testing_generator_test.rb, test/test_helper.rb
Use `with_test_suite` helper to clean up existing test setup. This was more relevant when exploring #1156, but is still helpful for generators that are test suite agnostic.
Also cleans up test setup by using a `file_fixture` that was missed in #1183
=> Test Cleanup: Refactor tests to use helper

NEWS.md, README.md, lib/generators/suspenders/install/web_generator.rb, lib/install/web.rb, test/generators/suspenders/install/web_generator_test.rb
Create generator to invoke all necessary generators. We add it to the `install`
namespace to provide flexibility should we add other installation options, such
as ones for API Only applications.
Introduces [template][] as a means to invoke `suspenders:install:web` when
creating a new application. This serves as an alternative to the system
executable that was removed.
We call `db:prepare` in the template to ensure `bin/setup` works as expected.
This is because we overrode that file to use `dev:prime`, which assume the
database has been created.
[template]: https://guides.rubyonrails.org/rails_application_templates.html
1. Generate a new Rails application:
```sh
rails new suspenders_qa \
--skip-test \
-d=postgresql \
-m=https://raw.githubusercontent.com/thoughtbot/suspenders/suspenders-3-0- …
```
=> Introduce `suspenders:install:web` and application template

lib/generators/suspenders/styles_generator.rb, lib/generators/templates/styles/postcss.config.js, test/fixtures/files/postcss.config.js, test/generators/suspenders/styles_generator_test.rb
Closes #1190
When including styles from `node_modules` via `@import`, we discovered that static assets referenced in those style sheets are not loaded, resulting in console errors.
Since [cssbundling-rails][] ships with [postcss-import][], we are already encouraging the use of importing styles from `node_modules`.
This commit aims to solve this problem by installing and configuring [postcss-url][]. Because `postcss-url` needs a directory to copy assets to, we create `app/assets/static` as part of the generator.
One thing to note is that we override the `postcss.config.js` generated by the cssbundling-rails installation script, which assumes that the following plugins have been installed.
- `postcss-import`
- `postcss-nesting`
- `autoprefixer`
Should that change, this file would be …
=> Styles Generator: Install `postcss-url`

lib/generators/suspenders/lint_generator.rb, test/generators/suspenders/lint_generator_test.rb
The recent release of [ESLint v9.0.0][] made it so [flat config][] is the new default.
Until we can update [thoughtbot/eslint-config][] to [support][] this version, we'll pin ESLint to `^8.9.0` in an effort to ship this next release of Suspenders.
[ESLint v9.0.0]: https://eslint.org/blog/2024/04/eslint-v9.0.0-released/
[flat config]:  https://eslint.org/blog/2024/04/eslint-v9.0.0-released/#flat-config-is-now-the-default-and-has-some-changes
[thoughtbot/eslint-config]: https://github.com/thoughtbot/eslint-config
[support]: https://github.com/thoughtbot/eslint-config/issues/10
=> Lint Generator: Account for breaking changes in ESLint

test/generators/suspenders/accessibility_generator_test.rb, test/generators/suspenders/factories_generator_test.rb, test/generators/suspenders/inline_svg_generator_test.rb
Rather than stub calls on Bundler, we simply assert the output of the generator to see if `bundle install` is called.
=> Test Cleanup: Update bundle assertions

test/generators/suspenders/accessibility_generator_test.rb, test/generators/suspenders/advisories_generator_test.rb, test/generators/suspenders/email_generator_test.rb, test/generators/suspenders/factories_generator_test.rb, test/generators/suspenders/inline_svg_generator_test.rb, test/generators/suspenders/jobs_generator_test.rb, test/generators/suspenders/lint_generator_test.rb, test/generators/suspenders/prerequisites_generator_test.rb, test/generators/suspenders/rake_generator_test.rb, test/generators/suspenders/setup_generator_test.rb, test/generators/suspenders/styles_generator_test.rb, test/generators/suspenders/tasks_generator_test.rb, test/generators/suspenders/testing_generator_test.rb, test/generators/suspenders/views_generator_test.rb
I no longer thing it's valuable to test if a generator has a custom description, because contributors would have to know to add these tests in the first place.
=> Test Cleanup: Remove generator description tests

lib/suspenders/cleanup/generate_readme.rb, test/suspenders/cleanup/generate_readme_test.rb
Follow-up to #1187
Since we derive the app name from a module name, we need to [titleize][] it so it reads better in the `README`.
Now `ExpectedAppName` will be rendered as `Expected App Name`.
[titleize]: https://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-titleize
=> Generated README: Titleize app name

lib/generators/suspenders/accessibility_generator.rb, lib/generators/suspenders/advisories_generator.rb, lib/generators/suspenders/ci_generator.rb, lib/generators/suspenders/email_generator.rb, lib/generators/suspenders/environments/development_generator.rb, lib/generators/suspenders/environments/production_generator.rb, lib/generators/suspenders/environments/test_generator.rb, lib/generators/suspenders/factories_generator.rb, lib/generators/suspenders/inline_svg_generator.rb, lib/generators/suspenders/jobs_generator.rb, lib/generators/suspenders/lint_generator.rb, lib/generators/suspenders/prerequisites_generator.rb, lib/generators/suspenders/rake_generator.rb, lib/generators/suspenders/setup_generator.rb, lib/generators/suspenders/styles_generator.rb, lib/generators/suspenders/tasks_generator.rb, lib/generators/suspenders/testing_generator.rb, lib/generators/suspenders/views_generator.rb, lib/suspenders/cleanup/generate_readme.rb
Follow-up to #1187
Update descriptions so that they work well in the `README.md` generated by `suspenders:clean_up:generate_readme`.
Also fixes a typo in `Suspenders::Cleanup::GenerateReadme`.
I tested this locally by running the following:
```
cd test/dummy
bin/rails suspenders:cleanup:generate_readme
cat README.md | pbcopy
```
Which produces the following:
---
Ruby: `>= 3.1`
Node: `20.11.1`
```
bin/setup
```
```
bin/rails dev
```
- Use `db/seeds.rb` to create records that need to exist in all environments.
- Use `lib/tasks/dev.rake` to create records that only need to exist in development.
Running `bin/setup` will run `dev:prime`.
- Use `bin/rails suspenders:db:migrate` to run [database migrations][]. This script ensures they are [reversible][].
- Use `bin/rails …
=> Generators: Update descriptions

CONTRIBUTING.md, FEATURES.md, README.md
Simplify `README` in an effort to highlight what really matters, and
remove references to each generator.
Instead, we introduce `FEATURES.md` which was modified from the `README`
generated by `bin/rails suspenders:cleanup:generate_readme`
Updates `CONTRIBUTING` guide to account for changes in the test suite.
Since this new build was generated from am [engine][], we no longer use
RSpec, and instead use the default test suite.
Remove reference to styleguide since the link is broken, and update link
to Suspenders boy to use HTTPS.
[engine]: https://guides.rubyonrails.org/engines.html
=> Documentation: Update README and CONTRIBUTING

Gemfile.lock, lib/generators/suspenders/install/web_generator.rb, lib/generators/suspenders/prerequisites_generator.rb, lib/generators/templates/prerequisites/node-version.tt, lib/suspenders/cleanup/generate_readme.rb, lib/suspenders/generators.rb, lib/suspenders/version.rb, suspenders.gemspec, test/generators/suspenders/install/web_generator_test.rb, test/generators/suspenders/prerequisites_generator_test.rb, test/suspenders/cleanup/generate_readme_test.rb, test/suspenders_test.rb
We were incorrectly assuming consumers had the version of Node installed that is declared in `Suspenders::NODE_LTS_VERSION`.
Because of this, we were generating a `.node-version` file with a version that was not installed on the user's system. This was a problem because when subsequent generators depending on Node where invoked, they would raise the following:
```
No preset version installed for command node
Please install a version by running one of the following:
asdf install nodejs 20.11.1
```
To account for this, we [borrow][] from Rails, but modify slightly. First, we look to see if `ENV["NODE_VERSION"]` is set. If not, we then look to see if Node is installed, and set the version via `node --version`. If neither of those values are present, we raise. This is because we can't use a …
=> Prerequisites: Use system version of Node

lib/generators/suspenders/install/web_generator.rb, lib/generators/suspenders/prerequisites_generator.rb, lib/install/web.rb, lib/suspenders/generators.rb, lib/suspenders/version.rb, test/generators/suspenders/install/web_generator_test.rb, test/generators/suspenders/prerequisites_generator_test.rb, test/suspenders/cleanup/generate_readme_test.rb, test/suspenders/generators_test.rb, test/suspenders_test.rb
Follow-up to #1201
It's not enough to ensure Node is installed. We also need to ensure the consumer has the supported minimum version installed. Otherwise, subsequent generators will raise errors like so:
```
error stylelint-config-standard-scss@13.1.0: The engine "node" is incompatible with this module. Expected version ">=18.12.0". Got "18.0.0"
error Found incompatible module.
```
We select `v20.0.0` as our minimum supported version because it is slated for Active LTS, but is not bleeding edge at [this time][]
We also raise when calling the template to avoid unnecessarily generating a new Rails application.
[this time]: https://nodejs.org/en/about/previous-releases
=> Prerequisites: Raise if Node version unsupported

README.md
Now that we no longer have a `suspenders` executable, we need to call
`rails new` with several options.
This commit documents how to use a `railsrc` file (or our dotfiles) to
simplify the process.
=> Promote dotfiles and railsrc

lib/suspenders/cleanup/organize_gemfile.rb, lib/tasks/suspenders.rake
Closes #1204
The `suspenders:cleanup:organize_gemfile` task was not loading the Rails
environment, resulting in the following error:
```
undefined method `starts_with?' for an instance of String
```
This was only happening on existing applications not generated by the
[application template][]
[application template]:
https://raw.githubusercontent.com/thoughtbot/suspenders/main/lib/install/web.rb
=> Include Rails environment as task dependency

Gemfile.lock, NEWS.md, README.md, lib/suspenders/version.rb
With the merge of #1135 and some subsequent follow-ups, we are ready to
officially release the next version of Suspenders.
Because we moved to [calver][] in #1106, we need to continue using
calver, since the latest release `20230113.0` is greater than `3.0.0`,
which was set in haste in ab3eb9735eabd3c3827c7b6a9cce7d59e079559e
In an effort to better brand this release, we give it the code name
"Tailored".
[calver]: https://calver.org
=> Prepare for "Tailored" release

lib/install/web.rb
Follow-up to #1206
Now that we've released `20240516.0`, we update the application template
to reference the released version on RubyGems.
This change doesn't require a new release, since this change just
affects the application template, and not the Gem itself.
=> Application Template: Used released version

FEATURES.md, lib/generators/suspenders/testing_generator.rb
While checking our guides, I've noticed that there are some typos in the Shoulda Matcher name.
=> Fix shoulda-matchers typo in guide and test

NEWS.md, lib/generators/suspenders/accessibility_generator.rb, test/generators/suspenders/accessibility_generator_test.rb
**This PR:**
- Closes [Issue 1228: Accessibility generator for capybara_accessible_selectors fails](https://github.com/thoughtbot/suspenders/issues/1228)
- Specifies a tag when installing capybara_accessible_selectors based on the [instructions](https://github.com/citizensadvice/capybara_accessible_selectors?tab=readme-ov-file#usage)
**Error without tag:**
```
Git error: command `git fetch --force --quiet --no-tags --depth 1 
-- https://github.com/citizensadvice/capybara_accessible_selectors.git 
refs/heads/HEAD:refs/heads/HEAD` 
in directory 
~/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/cache/bundler/git/capybara_accessible_selectors-7e28584b80a657a0689a0e8e8831f0d4fc91cb20 has failed.
Revision  does not exist in the repository …
```
=> Specify a tag when installing capybara_accessible_selectors

NEWS.md, README.md, lib/generators/suspenders/install/web_generator.rb, lib/install/web.rb
**This PR:**
- Fixes [Issue 1229: How do we want to handle un-released versions?](https://github.com/thoughtbot/suspenders/issues/1229)
- Allows passing a `--suspenders-main` parameter to use the `main` branch of suspenders instead of the latest released version
- Updates documentation to suggest `skip-rubocop` over `skip_rubocop`
**Example:**
```
rails new app_name \
--suspenders-main \
--skip-rubocop \
--skip-test \
-d=postgresql \
-m=https://raw.githubusercontent.com/thoughtbot/suspenders/main/lib/install/web.rb
```
Co-authored-by: Steve Polito <stevepolito@hey.com>
=> Allow running against suspenders main

lib/suspenders/cleanup/generate_readme.rb
**This PR:**
- Fixes [issue 1222: README instructions for running the development server are wrong](https://github.com/thoughtbot/suspenders/issues/1222)
=> Fix generate_readme for running the dev server

NEWS.md, lib/install/web.rb
Closes #1224
It's unclear why we need to run migrations, since we're already calling
[db:prepare][dbp] which does the following:
> If the database exists but the tables have not been created, the
command will load the schema, run any pending migrations, dump the
updated schema, and finally load the seed data. See the Seeding Data
documentation for more details.
However, I found that calling `db:migrate` in the application template
worked.
[dbp]: https://guides.rubyonrails.org/active_record_migrations.html#preparing-the-database
=> Ensure `bin/setup` works

lib/generators/suspenders/ci_generator.rb, test/generators/suspenders/ci_generator_test.rb, test/test_helper.rb
Since we switched to using `.yml` for YAML files in #1246, generating the CI config would clash and request the user intervene. We force the template to overwrite instead.
Completes #1243.
=> Force creation of GitHub Actions CI workflow
