thoughtbot/suspenders

README.md, lib/suspenders/app_builder.rb, lib/suspenders/generators/app_generator.rb, spec/features/heroku_spec.rb, spec/support/fake_heroku.rb
Most useful are likely:
* `--addons`
* `--region`
=> Allow additional Heroku flags

lib/suspenders/app_builder.rb
https://github.com/thoughtbot/suspenders/issues/407
https://github.com/thoughtbot/suspenders/issues/461
=> Set default_url_options to ENV["HOST"] on servers

lib/suspenders/app_builder.rb
Before:
config.serve_static_files = ENV['RAILS_SERVE_STATIC_FILES'].present? 
config.static_cache_control = "public, max-age=#{1.year.to_i}"
After:
config.serve_static_files = ENV['RAILS_SERVE_STATIC_FILES'].present?
config.static_cache_control = "public, max-age=#{1.year.to_i}"
=> Correctly indent config.static_cache_control line

lib/suspenders/app_builder.rb
I think this should have been removed in #299.
=> Remove factories_spec_rake_task method

lib/suspenders/app_builder.rb, templates/_flashes.html.erb, templates/flashes_helper.rb
We sometimes use the flash for things such as
"sign up" in order to send data to analytics systems
such as Mixpanel.
We've then ended up doing the following on a number of projects.
=> Only display user-facing flashes

NEWS.md, README.md, lib/suspenders/app_builder.rb, lib/suspenders/generators/app_generator.rb, spec/features/new_project_spec.rb
=> Inject spring into binstubs

suspenders.gemspec
We released Bitters 1.1 a bit ago…so this updates to that!
cc: @whmii Maybe we add updating Suspenders as a checklist for Bitters releases?
=> Update to Bitters 1.1

NEWS.md, lib/suspenders/version.rb
=> Releasing version 1.34

templates/sample.env
Should close https://github.com/thoughtbot/suspenders/issues/570
=> Set puma workers to 1 in .sample.env to play nice with web-console

NEWS.md, lib/suspenders/version.rb
=> Updates version to 1.37.0

bin/suspenders
Instead of printing default output, provide a more helpful
prompt with more info on what went wrong and
directions on how to get help.
Closes #730
=> Adds handling for ARGV.empty?

templates/Gemfile.erb
This fixes the build for me locally.
=> Upgrade bourbon to 5.0.0.beta.6

spec/features/new_project_spec.rb
Reads environment files once per file run.
=> Extract methods in new_project_spec file

suspenders.gemspec
Changes from Bitters 1.3 to 1.4: https://github.com/thoughtbot/bitters/blob/master/CHANGELOG.md#140---2016-08-10
=> Update Bitters to 1.4

NEWS.md, lib/suspenders/generators/stylesheet_base_generator.rb
I’m expecting this to be the final beta before release.
=> Update Bourbon to 5.0.0.beta.7

spec/features/new_project_spec.rb, templates/bin_setup_review_app.erb
I think it makes it easier to edit it
=> Update bin/setup-review-app to use sh variables

spec/features/new_project_spec.rb, templates/_analytics.html.erb
I can’t find a change log for the snippet, but I imagine we want to keep this updated.
=> Update Segment snippet to 4.0.0

templates/bin_setup_review_app.erb
`-a` is expanded to `--app` in the other occurrences in the file, so let
us expand it for consistency.
=> Expand `-a` flag in `bin/setup_review_app`

README.md, lib/suspenders/adapters/heroku.rb, lib/suspenders/app_builder.rb, lib/suspenders/generators/app_generator.rb, spec/features/heroku_spec.rb
This helps distinguish environments for errors.
Related:
ee60953dd81a6e3ba27a6a4ec1d3b96cda9215f9
=> Configure HONEYBADGER_ENV for staging, production

spec/support/suspenders.rb
Rails loads and configures the engines, including Honeybadger. Let's
take a walk through Honeybadger.
We make our way into `Honeybadger::Config#init!`, which calls
`#load!`. `Honeybadger#load!` sets the revision; this is used so Honeybadger
knows which release you are deploying. It figures out the revision in
`Honeybadger::Util::Revision.detect`:
```
def detect(root = Dir.pwd)
from_heroku || from_capistrano(root) || from_git
end
private
def from_heroku
ENV['HEROKU_SLUG_COMMIT']
end
def from_capistrano(root)
file = File.join(root, 'REVISION')
return nil unless File.file?(file)
File.read(file).strip rescue nil
end
def from_git
return nil unless File.directory?('.git')
`git rev-parse HEAD`.strip rescue nil
end
```
The `#from_git` is the problem: it calls `git rev-parse` on a git repo
that …
=> Silence git errors in test output

README.md, lib/suspenders/generators/stylesheet_base_generator.rb, spec/features/new_project_spec.rb, templates/application.scss
=> Remove Refills

spec/features/production/email_spec.rb, spec/support/match_contents_matcher.rb, spec/support/suspenders.rb
This is the first isolated test for a generator in this project. It
introduces a few new test helpers:
- `#with_app` takes a block and runs the block after ensuring a fresh
app.
- `#generate` runs the specified generator.
- `#match_contents` is a matcher that takes a regexp as an argument and
applies in the context for a filename expectation. It reads the file
within the dummy app and returns whether the given regexp matches the
contents of the file.
- `#rails_new` generates a Rails app.
- `#system_rails_bin` is the Rails binary.
- `#project_rails_bin` is the `bin/rails` within an app.
This test runs in isolation in approximately five seconds on my
computer. This is both slow and one of the fastest tests in the repo.
---
While here, remove two race conditions because filesystem race …
=> Test the suspenders:production:email generator

templates/suspenders_layout.html.erb.erb
The Open Directory Project has closed down.
=> Remove noodp robots meta tag

README.md
updating as a result of this commit https://github.com/thoughtbot/suspenders/commit/9accc4314eab8ba36c5cb1ee51faf27ee42c99c6#diff-8312ad0561ef661716b48d09478362f3
=> Remove Flutie reference in README

lib/suspenders/version.rb
Previously it was 5.2.0. Currently it is 2.5.3 (stable) version
=> Update rails version

README.md, lib/suspenders/generators/stylesheet_base_generator.rb, spec/features/new_project_spec.rb, templates/application.scss
We tend to use CSS Grid instead of [Neat][neat] these days.
[neat]: https://github.com/thoughtbot/neat
=> Remove Neat

lib/suspenders/generators/stylesheet_base_generator.rb, suspenders.gemspec
- [Bitters' change log](https://github.com/thoughtbot/bitters/blob/master/CHANGELOG.md)
- [Bourbon's change log](https://github.com/thoughtbot/bourbon/blob/master/CHANGELOG.md#600---2019-07-10)
=> Update bitters to 2.0, bourbon to 6.0

CONTRIBUTING.md, GOALS.md
This is something we've been working toward for half a decade now, so
it's best to document our intentions here for other contributors and our
own direction.
=> Document the generator goals

README.md
i get a 404 html page when using the curl command
=> fix hub install instructions

.standard.yml, spec/features/new_project_spec.rb, templates/partials/db_optimizations_configuration.rb
i'm still getting a bootsnap related error when running locally and a puma compile error when running the tests locally so i'm making a pull requests to see if the tests pass on travis
see #1053
=> fix broken development config

lib/suspenders/generators/json_generator.rb, spec/features/new_project_spec.rb, spec/suspenders/generators/json_generator_spec.rb, templates/oj.rb
Closes #1049
This commit adds an initializer to [optimize oj for use with Rails][oj]
[oj]: https://github.com/ohler55/oj/blob/develop/pages/Rails.md
=> Configure oj for Rails

README.md
=> ./bin/rails -> bin/rails

test/test_helper.rb
Follow-up to #1176
This was missed. I'm still not sure how the code that introduced did not fail in CI.
=> Fix missing linting violation

lib/generators/suspenders/install/web_generator.rb, lib/generators/templates/install/web/CONTRIBUTING.md, lib/suspenders/cleanup/generate_readme.rb
Generate contributing guide when suspending a new Rails application. Update generated `README.md` to point to contributing guide.
=> Install Generator: Generate `CONTRIBUTING.md`

.github/workflows/dynamic-security.yml, SECURITY.md
Adds CI workflow to dynamically update `SECURITY.md` anytime its
[source][] changes.
[source]: https://github.com/thoughtbot/templates/blob/main/SECURITY.md.template
=> CI: Add dynamic SECURITY.md

NEWS.md
**This PR:**
- Updates `NEWS.md` with the fix from [PR 1231: Fix generate_readme for running the dev server](https://github.com/thoughtbot/suspenders/pull/1231) in response to this [reminder](https://github.com/thoughtbot/suspenders/pull/1231#issuecomment-2427646303)
=> Update NEWS.md with fix for issue 1222
